const K='studyflow.v1',$=s=>document.querySelector(s),uid=()=>Math.random().toString(36).slice(2,9),
day=t=>new Date(t).toLocaleDateString('sv'),pad=n=>String(n).padStart(2,'0'),
fmt=s=>{s=Math.max(0,Math.round(s));return pad(s/60|0)+':'+pad(s%60)},
hm=s=>{const m=Math.round(s/60);return m>=60?(m/60|0)+'h'+pad(m%60)+'min':m+'min'},
esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),
add=(d,n)=>day(Date.now()+n*864e5);
let S,page='home',sub='',tab='hoje',done=null,chat=[];
function demo(){const m=[['Matemática','#2f6bff'],['Português','#c24bd6'],['História','#f5a623'],['Geografia','#19b6c9'],['Biologia','#22c58b'],['Física','#ef4b5b'],['Química','#8b5cf6'],['Inglês','#ec7a3c']].map(([name,color])=>({id:uid(),name,color}));
const id=n=>m.find(x=>x.name==n).id,ses=[];[[0,'Matemática',1500],[0,'História',1200],[1,'Biologia',1800],[2,'Matemática',2400],[3,'Português',1500],[4,'Física',1200],[5,'Matemática',3000],[6,'Química',1500]].forEach(([d,n,s])=>{const t=Date.now()-d*864e5-36e5;ses.push({id:uid(),subject:id(n),topic:'Revisão',startedAt:t,endedAt:t+s*1e3,duration:s,status:'completed'})});
return{user:{name:'Dudu',year:'',school:''},subjects:m,tasks:[['Revisar matemática','Matemática',0,40,'Alta'],['Fazer trabalho de história','História',0,90,'Média'],['Estudar biologia','Biologia',0,30,'Média'],['Ler capítulo de português','Português',0,40,'Baixa'],['Redação','Português',3,60,'Média'],['Lista de exercícios (física)','Física',5,60,'Média']].map(([title,s,d,min,pr])=>({id:uid(),title,subject:id(s),due:add(0,d),min,pr,done:title=='Revisar matemática'})),
grades:[['Matemática','Prova 1',8.5,2],['Matemática','Trabalho',7.5,1],['Português','Prova 1',7.8,2],['História','Prova 1',9,2],['Biologia','Prova 1',8.2,2]].map(([s,name,v,w])=>({id:uid(),subject:id(s),name,v,w})),
exams:[{id:uid(),subject:id('Matemática'),date:add(0,8)},{id:uid(),subject:id('Física'),date:add(0,15)}],sessions:ses,reviews:[['Revolução Industrial','História',0],['Equações do 2º grau','Matemática',1],['Célula eucarionte','Biologia',3]].map(([topic,s,d])=>({id:uid(),topic,subject:id(s),due:add(0,d),done:false})),active:null}}
const empty=()=>({user:{name:'Dudu',year:'',school:''},subjects:[],tasks:[],grades:[],exams:[],sessions:[],reviews:[],active:null});
try{S=JSON.parse(localStorage[K])}catch(e){}S=S||demo();
const save=()=>localStorage[K]=JSON.stringify(S),sj=id=>S.subjects.find(s=>s.id==id)||{name:'—',color:'#888'};
const opts=(sel)=>S.subjects.map(s=>`<option value="${s.id}" ${s.id==sel?'selected':''}>${esc(s.name)}</option>`).join('');
// ---- sessões: tempo real = soma dos segmentos [início, fim]
const elapsed=a=>a.segs.reduce((t,[s,e])=>t+((e??Date.now())-s),0)/1e3,running=a=>a&&a.segs.at(-1)[1]==null;
function startS(){const subject=$('#ss').value,topic=$('#st').value.trim()||'Estudo livre';let min=+$('#sd').value;if(!min)min=Math.max(1,+prompt('Minutos:','30')||25);if(!subject)return alert('Crie uma matéria primeiro.');
S.active={subject,topic,planned:min*60,startedAt:Date.now(),segs:[[Date.now(),null]],seen:Date.now()};page='timer';save();render()}
function pause(){const a=S.active;if(running(a))a.segs.at(-1)[1]=Date.now();else a.segs.push([Date.now(),null]);save();render()}
function finish(cancel){const a=S.active;if(!a)return;if(running(a))a.segs.at(-1)[1]=Date.now();S.active=null;
if(cancel||elapsed(a)<5){save();return go('study')}
const r={id:uid(),subject:a.subject,topic:a.topic,startedAt:a.startedAt,endedAt:a.segs.at(-1)[1],duration:Math.round(elapsed(a)),status:'completed'};S.sessions.push(r);done=r;page='timer';save();render()}
function rate(n){const d=[1,2,4,7,14][n-1];S.reviews.push({id:uid(),topic:done.topic,subject:done.subject,due:add(0,d),done:false});done=null;save();go('study')}
setInterval(()=>{const a=S.active;if(!a)return;if(running(a)){a.seen=Date.now();localStorage[K]=JSON.stringify(S);if(elapsed(a)>=a.planned)return finish()}const t=$('#tm');if(t){t.textContent=fmt(a.planned-elapsed(a));const g=$('#rg'),C=2*Math.PI*78;if(g)g.setAttribute('stroke-dashoffset',C*Math.min(1,elapsed(a)/a.planned))}},1000);
// recuperação: se a aba foi fechada com sessão rodando, o tempo conta só até o último sinal de vida
if(S.active&&running(S.active)){S.active.segs.at(-1)[1]=S.active.seen;S.active.recover=true;save()}
// ---- métricas
const dur=(f)=>S.sessions.filter(f).reduce((t,s)=>t+s.duration,0),today=()=>day(Date.now());
function streak(){let n=0,i=0;const ds=new Set(S.sessions.map(s=>day(s.startedAt)));if(!ds.has(add(0,0)))i=-1;while(ds.has(add(0,i-n)))n++;return n}
function avg(id){const g=S.grades.filter(g=>g.subject==id),w=g.reduce((t,x)=>t+x.w,0);return w?g.reduce((t,x)=>t+x.v*x.w,0)/w:null}
const f1=v=>v==null?'—':v.toFixed(1).replace('.',',');
const week=()=>[...Array(7)].map((_,i)=>{const d=add(0,i-6);return[new Date(d+'T12:00').toLocaleDateString('pt-BR',{weekday:'short'}).slice(0,3),dur(s=>day(s.startedAt)==d)/60]});
const chart=()=>{const w=week(),m=Math.max(30,...w.map(x=>x[1]));return`<div class="chart">${w.map(([l,v])=>`<div><b style="height:${v/m*80}px"></b>${l}</div>`).join('')}</div>`};
// ---- tarefas
const T={toggle(id){const t=S.tasks.find(t=>t.id==id);t.done=!t.done;save();render()},del(id){S.tasks=S.tasks.filter(t=>t.id!=id);save();render()},edit(id){const t=S.tasks.find(t=>t.id==id),n=prompt('Editar tarefa:',t.title);if(n){t.title=n;save();render()}},
add(){const title=$('#tt').value.trim();if(!title)return;S.tasks.push({id:uid(),title,subject:$('#ts').value,due:$('#td').value||today(),min:+$('#tm2').value||30,pr:$('#tp').value,done:false});save();render()}};
// ---- páginas
let form=0,range='semana',ttab='hoje',rtab='pend';
const IC={Matemática:'➗',Português:'📖',História:'🏛️',Geografia:'🌎',Biologia:'🍃',Física:'⚛️',Química:'🧪',Inglês:'🔤'},ic=n=>IC[n]||'📘';
const hd=(t,l='',back)=>`<div class="top">${back?`<button class="ib" onclick="${back}">←</button>`:''}<h1>${t}</h1>${l}</div>`;
const dm=d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'});
const taskRow=t=>`<div class="t ${t.done?'d':''}"><input type="checkbox" ${t.done?'checked':''} onchange="T.toggle('${t.id}')"><div class="grow"><div class="tt">${esc(t.title)}</div><small>${t.min>=60?(t.min/60|0)+'h'+(t.min%60?(t.min%60)+'min':''):t.min+'min'} · ${esc(sj(t.subject).name)} · ${t.due.slice(8)}/${t.due.slice(5,7)}</small></div><button class="mini" onclick="T.edit('${t.id}')">✎</button><button class="mini" onclick="T.del('${t.id}')">✕</button></div>`;
const taskForm=()=>`<form class="card f" onsubmit="event.preventDefault();T.add()"><input id="tt" placeholder="Nova tarefa" required><div class="row"><select id="ts">${opts()}</select><input id="td" type="date" value="${today()}"></div><div class="row"><input id="tm2" type="number" min="1" placeholder="Minutos" value="30"><select id="tp"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div><button class="p">Adicionar tarefa</button></form>`;
const xp=()=>Math.round(dur(()=>1)/60)+S.reviews.filter(r=>r.done).length*20,lvl=()=>(xp()/500|0)+1;
const ACH=()=>{const m=dur(()=>1)/60,dias=new Set(S.sessions.map(s=>day(s.startedAt))).size,tp=new Set(S.sessions.map(s=>s.topic)).size,st=streak();return[['👣','Primeiro passo',S.sessions.length>=1],['🔥','7 dias seguidos',st>=7],['🧭','10 tópicos',tp>=10],['⏱️','1h de foco',m>=60],['📚','5h de foco',m>=300],['🏆','10h de foco',m>=600],['🔁','Primeira revisão',S.reviews.some(r=>r.done)],['🌟','30 dias seguidos',st>=30]]};
const P={
home(){const pend=S.tasks.filter(t=>!t.done),hj=pend.filter(t=>t.due<=today()),ex=S.exams.filter(e=>e.date>=today()).sort((a,b)=>a.date>b.date?1:-1),e=ex[0],dl=e?Math.round((new Date(e.date)-new Date(today()))/864e5):0;
return`<div class="top"><h1 class="logo">🎓 <span>Study<b>Flow</b></span></h1><button class="ib" onclick="go('more','rev')">🔔</button><button class="ib" onclick="go('more','prof')">👤</button></div>
<h1>Olá, ${esc(S.user.name)}!</h1><p class="mu" style="margin:4px 0 14px">Disciplina hoje, liberdade amanhã. 🚀</p>
<div class="card row" onclick="go('more','prof')">🔥<div class="grow"><b>${streak()?'Você está indo muito bem!':'Estude hoje e comece sua sequência!'}</b><br><small>${streak()} dias de sequência</small></div>›</div>
<div class="grid"><div class="card"><span class="sq" style="background:#12306b;width:30px;height:30px;font-size:15px">⏱</span><div class="big">${hm(dur(s=>day(s.startedAt)==today()))}</div><small>estudados hoje</small></div><div class="card"><span class="sq" style="background:#0f4a45;width:30px;height:30px;font-size:15px">✔</span><div class="big">${pend.length}</div><small>tarefas pendentes</small></div><div class="card"><span class="sq" style="background:#3a2a7a;width:30px;height:30px;font-size:15px">📝</span><div class="big">${ex.length}</div><small>provas próximas</small></div></div>
<h2>Próxima prova</h2>${e?`<div class="card row" onclick="go('timer')"><span class="sq" style="background:var(--blue)">${ic(sj(e.subject).name)}</span><div class="grow"><b>${esc(sj(e.subject).name)}</b><br><small>${dm(e.date)}<br>em ${dl} dias</small></div>›</div>`:'<div class="card mu">Nenhuma prova cadastrada (em Matérias).</div>'}
<div class="row"><h2 class="grow">Tarefas de hoje</h2><small style="color:#4d8bff" onclick="go('tasks')">Ver todas →</small></div><div class="card">${hj.map(taskRow).join('')||'<span class="mu">Nada para hoje 🎉</span>'}</div>
<button class="p" onclick="go('timer')">Começar a estudar</button><button class="fab" onclick="go('tasks');form=1;render()">+</button>`},
subjects(){return`${hd('📚 Matérias','')}${S.subjects.map(s=>{const a=avg(s.id),n=S.sessions.filter(x=>x.subject==s.id),tp=new Set(n.map(x=>x.topic)).size,p=a?Math.round(a*10):0;return`<div class="card"><div class="row"><span class="sq" style="background:${s.color}">${ic(s.name)}</span><div class="grow"><b>${esc(s.name)}</b><br><small>${tp} tópicos · ${n.length} sessões · média ${f1(a)}</small></div><small>${p}%</small></div><div class="bar"><i style="width:${p}%;background:${s.color}"></i></div>${need(s.id)}</div>`}).join('')}
<h2>Cadastrar</h2><form class="card row" onsubmit="event.preventDefault();addSub()"><input id="sn" placeholder="Nova matéria" required class="grow"><button class="p" style="width:auto">+</button></form>
<form class="card f" onsubmit="event.preventDefault();addGrade()"><select id="gs">${opts()}</select><input id="gn" placeholder="Avaliação (ex: Prova 1)" required><div class="row"><input id="gv" type="number" step="0.1" min="0" max="10" placeholder="Nota" required><input id="gw" type="number" step="0.5" min="0.5" value="1"></div><button class="p">Salvar nota</button></form>
<form class="card row" onsubmit="event.preventDefault();addExam()"><select id="es">${opts()}</select><input id="ed" type="date" required><button class="p" style="width:auto">Prova</button></form>`},
tasks(){const p=S.tasks.filter(t=>!t.done),h=today(),L={hoje:p.filter(t=>t.due<=h),semana:p.filter(t=>t.due<=add(0,7)),todas:S.tasks},prox=p.filter(t=>t.due>h);
return`${hd('📋 Tarefas',`<button class="ib" onclick="form=!form;render()">+</button>`)}${form?taskForm():''}<div class="tabs">${[['hoje','Hoje'],['semana','Semana'],['todas','Todas']].map(([k,l])=>`<button class="${ttab==k?'on':''}" onclick="ttab='${k}';render()">${l}</button>`).join('')}</div>
<p style="margin-bottom:8px">${new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</p><div class="card">${L[ttab].map(taskRow).join('')||'<span class="mu">Nenhuma tarefa aqui.</span>'}</div>${ttab=='hoje'&&prox.length?`<h2>Próximas tarefas</h2><div class="card">${prox.slice(0,4).map(taskRow).join('')}</div>`:''}`},
study(){const w=dur(s=>s.startedAt>=Date.now()-(range=='hoje'?0:range=='semana'?6:29)*864e5&&(range!='hoje'||day(s.startedAt)==today())),a=S.active,all=dur(()=>1);
const ranges=[['hoje','Hoje'],['semana','Semana'],['mes','Mês']],ws=week(),m=Math.max(30,...ws.map(x=>x[1]));
return`${hd('📊 Estatísticas','')}${a?`<div class="card row" onclick="go('timer')"><b class="grow">⏱ Sessão em andamento</b>›</div>`:`<button class="p" onclick="go('timer')">Iniciar sessão de estudo</button>`}
<div class="tabs">${ranges.map(([k,l])=>`<button class="${range==k?'on':''}" onclick="range='${k}';render()">${l}</button>`).join('')}</div>
<div class="card"><small>Tempo total de estudo</small><div class="big" style="font-size:32px">${hm(w)}</div><div class="chart" style="margin-top:12px">${ws.map(([l,v])=>`<div><b style="height:${v/m*100}px"></b></div>`).join('')}</div><div class="lb">${ws.map(x=>`<span>${x[0]}</span>`).join('')}</div></div>
<div class="card"><b>Por matéria</b>${S.subjects.map(s=>[s,dur(x=>x.subject==s.id)]).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]).map(([s,v])=>`<div style="margin-top:12px"><div class="row"><span style="width:12px;height:12px;border-radius:4px;background:${s.color}"></span><span class="grow">${esc(s.name)}</span><small>${hm(v)} · ${Math.round(v/all*100)}%</small></div><div class="bar"><i style="width:${v/all*100}%;background:${s.color}"></i></div></div>`).join('')||'<p class="mu">Sem sessões ainda.</p>'}</div>
<div class="grid g2"><div class="card"><small>Sessões</small><div class="big">${S.sessions.length}</div></div><div class="card"><small>Duração média</small><div class="big">${S.sessions.length?hm(all/S.sessions.length):'—'}</div></div></div>`},
timer(){const a=S.active;
if(done)return`${hd('Estudo concluído!','')}<div class="card"><p class="mu">${esc(sj(done.subject).name)} · ${esc(done.topic)} · ${hm(done.duration)}</p><h2>Como você se sente sobre esse conteúdo?</h2>${['Não entendi','Entendi pouco','Entendi razoavelmente','Entendi bem','Dominei'].map((t,i)=>`<button class="g" style="border:1px solid var(--line)" onclick="rate(${i+1})">${i+1} · ${t}</button>`).join('')}</div>`;
const run=a&&running(a),n=S.sessions.length+1,pl=a?a.planned:(+(window.dsel||25))*60,left=a?pl-elapsed(a):pl,C=2*Math.PI*78,pr=a?Math.min(1,elapsed(a)/pl):0;
const ring=`<svg class="ring" width="200" height="200" viewBox="0 0 200 200"><circle cx="100" cy="100" r="78" fill="none" stroke="#12255a" stroke-width="9"/><circle id="rg" cx="100" cy="100" r="78" fill="none" stroke="#2f6bff" stroke-width="9" stroke-linecap="round" stroke-dasharray="${C}" stroke-dashoffset="${C*pr}" transform="rotate(-90 100 100)"/><text x="100" y="104" text-anchor="middle" class="tm" id="tm" fill="#fff">${fmt(left)}</text><text x="100" y="128" text-anchor="middle" fill="#8497c4" font-size="13">${a?(run?'Tempo restante':'Pausado'):'Tempo de foco'}</text></svg>`;
if(a)return`${hd('⏱ Foco','','go(\'study\')')}${a.recover?`<div class="card">Sessão interrompida (aba fechada). Contamos só até ${new Date(a.seen).toLocaleTimeString('pt-BR')}.<button class="p" style="margin-top:10px" onclick="S.active.recover=0;pause()">Recuperar e continuar</button><button class="g" onclick="finish()">Encerrar e salvar</button></div>`:''}
<div class="card row"><span class="sq" style="background:var(--blue)">${ic(sj(a.subject).name)}</span><b>${esc(sj(a.subject).name)}</b></div>${ring}<p class="c" style="text-align:center">Sessão #${n} · ${Math.round(pl/60)} min</p><div class="card" style="margin-top:14px">${esc(a.topic)}</div>
${a.recover?'':`<button class="p" onclick="pause()">${run?'⏸ Pausar':'▶ Continuar'}</button><button class="g" style="border:1px solid var(--line)" onclick="finish()">Finalizar sessão</button><button class="g" onclick="finish(1)">Cancelar</button>`}`;
return`${hd('⏱ Pomodoro','','go(\'study\')')}<div class="card f"><select id="ss">${opts()}</select><input id="st" placeholder="Conteúdo (ex: Equações do 2º grau)"><select id="sd" onchange="window.dsel=this.value;if(this.value!=0){$('#tm').textContent=fmt(this.value*60)}"><option ${dsel==15?'selected':''}>15</option><option ${dsel==25?'selected':''}>25</option><option ${dsel==45?'selected':''}>45</option><option ${dsel==60?'selected':''}>60</option><option value="0">Personalizado</option></select></div>${ring}<button class="p" onclick="startS()">▶ Começar estudo</button>`},
more(){const rv=S.reviews.filter(r=>(rtab=='pend')!=r.done).sort((a,b)=>a.due>b.due?1:-1);
if(sub=='tutor')return`${hd('🤖 Tutor','',"sub='';render()")}<div class="row" style="align-items:flex-start"><div class="msg">Oi, ${esc(S.user.name)}! 👋 Me conta o que você quer aprender hoje. Posso explicar, dar exercícios, resumir o conteúdo ou ajudar a revisar.</div></div>${chat.map(m=>`<div class="msg ${m.u?'u':''}">${esc(m.t)}</div>`).join('')}<div style="margin:14px 0">${[['📖','Explicar um conteúdo'],['✅','Resolver exercícios'],['📝','Fazer um resumo'],['🔁','Revisar um assunto'],['🏆','Simulado']].map(([i,b])=>`<button class="qb" onclick="$('#ti').value='${b}: ';$('#ti').focus()">${i} ${b}</button>`).join('')}</div><form class="row" onsubmit="event.preventDefault();ask()"><input id="ti" class="grow" placeholder="Digite sua dúvida aqui..."><button class="ib">➤</button></form>`;
if(sub=='rev')return`${hd('🧠 Revisões','',"sub='';render()")}<div class="tabs">${[['pend','Pendentes'],['conc','Concluídas']].map(([k,l])=>`<button class="${rtab==k?'on':''}" onclick="rtab='${k}';render()">${l}</button>`).join('')}</div><div class="card"><small>Ao terminar uma sessão, o app agenda revisões espaçadas para você não esquecer!</small></div><div class="card">${rv.map(r=>`<div class="t"><div class="grow">${esc(r.topic)}<br><small>${r.due<=today()?'Hoje':r.due.slice(8)+'/'+r.due.slice(5,7)} · ${esc(sj(r.subject).name)}</small></div><button class="mini" onclick="S.reviews.find(x=>x.id=='${r.id}').done=${rtab=='pend'};save();render()">${rtab=='pend'?'✓':'↺'}</button></div>`).join('')||'<span class="mu">Nada por aqui.</span>'}</div><small>Você já revisou ${S.reviews.filter(r=>r.done).length} assuntos.</small>`;
if(sub=='prof')return`${hd('📈 Seu progresso','',"sub='';render()")}<div class="card row"><span class="sq" style="width:64px;height:64px;border-radius:50%;background:#12306b;font-size:30px">👤</span><div class="grow"><b style="font-size:19px">Nível ${lvl()}</b><br><small>Estudante</small><div class="bar"><i style="width:${xp()%500/5}%"></i></div><small style="float:right">${xp()%500} / 500 XP</small></div></div><input class="card" style="width:100%" value="${esc(S.user.name)}" onchange="S.user.name=this.value.trim()||'Dudu';save()">
<div class="grid g2"><div class="card"><div class="big">${streak()} dias</div><small>sequência atual</small></div><div class="card"><div class="big">${new Set(S.sessions.map(s=>day(s.startedAt))).size}</div><small>dias no total</small></div><div class="card"><div class="big">${S.reviews.filter(r=>r.done).length}</div><small>revisões concluídas</small></div><div class="card"><div class="big">${S.sessions.length}</div><small>sessões</small></div></div><h2>Conquistas</h2><div class="card" style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px">${ACH().map(([i,n,ok])=>`<div class="ach ${ok?'':'off'}"><div>${i}</div>${n}</div>`).join('')}</div>`;
return`${hd('Mais','')}${[['rev','🧠','Revisões'],['prof','📈','Meu progresso e conquistas'],['tutor','🤖','Tutor']].map(([k,i,l])=>`<div class="card row" onclick="sub='${k}';render()"><span class="sq" style="background:#12306b">${i}</span><b class="grow">${l}</b>›</div>`).join('')}<h2>Dados</h2><button class="g" style="border:1px solid var(--line)" onclick="if(confirm('Apagar tudo e começar do zero?')){S=empty();save();render()}">Apagar dados de demonstração</button><button class="g" onclick="if(confirm('Restaurar demonstração?')){S=demo();save();render()}">Restaurar demonstração</button>`}};
function need(id){const g=S.grades.filter(g=>g.subject==id);if(!g.length)return'';const W=g.reduce((t,x)=>t+x.w,0),sum=g.reduce((t,x)=>t+x.v*x.w,0),n=(8*(W+1)-sum);return`<small class="mu">Para fechar com 8,0, tire ~${f1(Math.max(0,n))} na próxima avaliação (peso 1).</small>`}
const addSub=()=>{S.subjects.push({id:uid(),name:$('#sn').value,color:'#2f6bff'});save();render()},addGrade=()=>{S.grades.push({id:uid(),subject:$('#gs').value,name:$('#gn').value,v:+$('#gv').value,w:+$('#gw').value||1});save();render()},addExam=()=>{S.exams.push({id:uid(),subject:$('#es').value,date:$('#ed').value});save();render()};
// IA: ponto de conexão futuro (API não configurada)
async function askAI(msg){return null}
async function ask(){const t=$('#ti').value.trim();if(!t)return;chat.push({u:1,t});const r=await askAI(t);chat.push({u:0,t:r||'IA ainda não configurada. Conecte uma API na função askAI() em app.js.'});render()}
window.dsel=25;const go=(p,sb='')=>{page=p;sub=sb;form=0;ttab='hoje';rtab='pend';range='semana';if(p!='timer')done=null;render()};
function render(){const items=[['home','⌂','Início'],['subjects','▤','Matérias'],['tasks','☑','Tarefas'],['study','▥','Estudos'],['more','⋯','Mais']],cur=page=='timer'?'study':page;
$('#nav').innerHTML=items.map(([k,i,l])=>`<a class="${cur==k?'on':''}" onclick="go('${k}')"><b>${i}</b>${l}</a>`).join('');$('#app').innerHTML=P[page]();scrollTo(0,0)}
render();
