const K='studyflow.v1',$=s=>document.querySelector(s),uid=()=>Math.random().toString(36).slice(2,9),
day=t=>new Date(t).toLocaleDateString('sv'),pad=n=>String(n).padStart(2,'0'),
fmt=s=>{s=Math.max(0,Math.round(s));return pad(s/60|0)+':'+pad(s%60)},
hm=s=>{const m=Math.round(s/60);return m>=60?(m/60|0)+'h'+pad(m%60)+'min':m+'min'},
esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),
add=(d,n)=>day(Date.now()+n*864e5);
let S,page='home',sub='',tab='hoje',done=null,chat=[];
function demo(){const m=[['Matemática','#2f6bff'],['Português','#c24bd6'],['História','#f5a623'],['Geografia','#19b6c9'],['Biologia','#22c58b'],['Física','#ef4b5b'],['Química','#8b5cf6'],['Inglês','#ec7a3c']].map(([name,color])=>({id:uid(),name,color}));
const id=n=>m.find(x=>x.name==n).id,ses=[];[[0,'Matemática',1500],[0,'História',1200],[1,'Biologia',1800],[2,'Matemática',2400],[3,'Português',1500],[4,'Física',1200],[5,'Matemática',3000],[6,'Química',1500]].forEach(([d,n,s])=>{const t=Date.now()-d*864e5-36e5;ses.push({id:uid(),subject:id(n),topic:'Revisão',startedAt:t,endedAt:t+s*1e3,duration:s,status:'completed'})});
return{user:{name:'Dudu',year:'',school:''},subjects:m,tasks:[['Revisar matemática','Matemática',0,40,'Alta'],['Fazer trabalho de história','História',0,90,'Média'],['Estudar biologia','Biologia',0,30,'Média'],['Ler capítulo de português','Português',0,40,'Baixa'],['Redação','Português',3,60,'Média'],['Lista de exercícios (física)','Física',5,60,'Média']].map(([title,s,d,min,pr])=>({id:uid(),title,subject:id(s),due:add(0,d),min,pr,done:title=='Revisar matemática'})),
grades:[['Matemática','Prova 1',8.5,2],['Matemática','Trabalho',7.5,1],['Português','Prova 1',7.8,2],['História','Prova 1',9,2],['Biologia','Prova 1',8.2,2]].map(([s,name,v,w])=>({id:uid(),subject:id(s),name,v,w})),
exams:[{id:uid(),subject:id('Matemática'),date:add(0,8)},{id:uid(),subject:id('Física'),date:add(0,15)}],sessions:ses,reviews:[['Revolução Industrial','História',0],['Equações do 2º grau','Matemática',1],['Célula eucarionte','Biologia',3]].map(([topic,s,d])=>({id:uid(),topic,subject:id(s),due:add(0,d),done:false})),active:null}}
const empty=()=>({user:{name:'Dudu',year:'',school:''},subjects:[],tasks:[],grades:[],exams:[],sessions:[],reviews:[],active:null});
try{S=JSON.parse(localStorage[K])}catch(e){}S=S||demo();
const save=()=>localStorage[K]=JSON.stringify(S),sj=id=>S.subjects.find(s=>s.id==id)||{name:'—',color:'#888'};
const opts=(sel)=>S.subjects.map(s=>`<option value="${s.id}" ${s.id==sel?'selected':''}>${esc(s.name)}</option>`).join('');
// ---- sessões: tempo real = soma dos segmentos [início, fim]
const elapsed=a=>a.segs.reduce((t,[s,e])=>t+((e??Date.now())-s),0)/1e3,running=a=>a&&a.segs.at(-1)[1]==null;
function startS(){const subject=$('#ss').value,topic=$('#st').value.trim()||'Estudo livre';let min=+dsel||25;if(!subject)return alert('Crie uma matéria primeiro.');
S.active={subject,topic,planned:min*60,startedAt:Date.now(),segs:[[Date.now(),null]],seen:Date.now()};page='timer';save();render()}
function pause(){const a=S.active;if(running(a))a.segs.at(-1)[1]=Date.now();else a.segs.push([Date.now(),null]);save();render(1)}
function finish(cancel){const a=S.active;if(!a)return;if(running(a))a.segs.at(-1)[1]=Date.now();S.active=null;
if(cancel||elapsed(a)<5){save();return go('study')}
const r={id:uid(),subject:a.subject,topic:a.topic,startedAt:a.startedAt,endedAt:a.segs.at(-1)[1],duration:Math.round(elapsed(a)),status:'completed'};S.sessions.push(r);done=r;page='timer';save();render()}
function rate(n){const d=[1,2,4,7,14][n-1];S.reviews.push({id:uid(),topic:done.topic,subject:done.subject,due:add(0,d),done:false});done=null;save();go('study')}
setInterval(()=>{const a=S.active;if(!a)return;if(running(a)){a.seen=Date.now();localStorage[K]=JSON.stringify(S);if(elapsed(a)>=a.planned)return finish()}const t=$('#tm');if(t){t.textContent=fmt(a.planned-elapsed(a));const g=$('#rg'),C=2*Math.PI*78;if(g)g.setAttribute('stroke-dashoffset',C*Math.min(1,elapsed(a)/a.planned))}},1000);
// recuperação: se a aba foi fechada com sessão rodando, o tempo conta só até o último sinal de vida
if(S.active&&running(S.active)){S.active.segs.at(-1)[1]=S.active.seen;S.active.recover=true;save()}
// ---- métricas
const dur=(f)=>S.sessions.filter(f).reduce((t,s)=>t+s.duration,0),today=()=>day(Date.now());
function streak(){let n=0,i=0;const ds=new Set(S.sessions.map(s=>day(s.startedAt)));if(!ds.has(add(0,0)))i=-1;while(ds.has(add(0,i-n)))n++;return n}
function avg(id){const g=S.grades.filter(g=>g.subject==id),w=g.reduce((t,x)=>t+x.w,0);return w?g.reduce((t,x)=>t+x.v*x.w,0)/w:null}
const f1=v=>v==null?'—':v.toFixed(1).replace('.',',');
const week=()=>[...Array(7)].map((_,i)=>{const d=add(0,i-6);return[new Date(d+'T12:00').toLocaleDateString('pt-BR',{weekday:'short'}).slice(0,3),dur(s=>day(s.startedAt)==d)/60]});
const chart=()=>{const w=week(),m=Math.max(30,...w.map(x=>x[1]));return`<div class="chart">${w.map(([l,v])=>`<div><b style="height:${v/m*80}px"></b>${l}</div>`).join('')}</div>`};
// ---- tarefas
const T={toggle(id){const t=S.tasks.find(t=>t.id==id);t.done=!t.done;save();render(1)},del(id){S.tasks=S.tasks.filter(t=>t.id!=id);save();render(1)},edit(id){const t=S.tasks.find(t=>t.id==id),n=prompt('Editar tarefa:',t.title);if(n){t.title=n;save();render(1)}},
add(){const title=$('#tt').value.trim();if(!title)return;S.tasks.push({id:uid(),title,subject:$('#ts').value,due:$('#td').value||today(),min:+$('#tm2').value||30,pr:$('#tp').value,done:false});save();render(1)}};
// ---- ícones (SVG)
const D={home:'<path d="M3 11l9-8 9 8"/><path d="M5 10v10h14V10"/>',book:'<path d="M4 19V5a2 2 0 0 1 2-2h13v14H6a2 2 0 0 0-2 2zM4 19a2 2 0 0 0 2 2h13"/>',tasks:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M9 12l2 2 4-4"/>',chart:'<path d="M5 20V10M12 20V4M19 20v-7"/>',more:'<circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/>',bell:'<path d="M6 16v-5a6 6 0 0 1 12 0v5l2 2H4z"/><path d="M10 21h4"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',clock:'<circle cx="12" cy="13" r="8"/><path d="M12 9v4l3 2M9 2h6"/>',flame:'<path d="M12 3c1 4 5 5 5 10a5 5 0 0 1-10 0c0-2 1-3 2-4 0 2 1 3 2 3 0-3-1-5 1-9z"/>',plus:'<path d="M12 5v14M5 12h14"/>',edit:'<path d="M4 20h4L19 9l-4-4L4 16z"/>',x:'<path d="M6 6l12 12M18 6L6 18"/>',back:'<path d="M15 5l-7 7 7 7"/>',chev:'<path d="M9 5l7 7-7 7"/>',send:'<path d="M3 11l18-8-8 18-2-8z"/>',play:'<path d="M7 4l13 8-13 8z"/>',pause:'<path d="M8 5v14M16 5v14"/>',brain:'<path d="M9 4a3 3 0 0 0-3 3 3 3 0 0 0-2 5 3 3 0 0 0 3 5 3 3 0 0 0 5 1V4a3 3 0 0 0-3 0zM15 4a3 3 0 0 1 3 3 3 3 0 0 1 2 5 3 3 0 0 1-3 5 3 3 0 0 1-5 1"/>',bot:'<rect x="4" y="8" width="16" height="12" rx="3"/><path d="M12 4v4M9 14h.01M15 14h.01"/>',trophy:'<path d="M8 4h8v6a4 4 0 0 1-8 0zM8 6H4v2a3 3 0 0 0 4 3M16 6h4v2a3 3 0 0 1-4 3M12 14v4M8 21h8"/>',calc:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6M9 12h.01M12 12h.01M15 12h.01M9 16h.01M12 16h.01M15 16h.01"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',flask:'<path d="M9 3h6M10 3v6l-5 10a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-10V3"/>',atom:'<circle cx="12" cy="12" r="1.5"/><ellipse cx="12" cy="12" rx="10" ry="4"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)"/>',leaf:'<path d="M5 19c0-9 5-14 15-14 0 10-5 15-14 15zM5 19l8-8"/>',bank:'<path d="M3 9l9-6 9 6M5 9v9M10 9v9M14 9v9M19 9v9M3 21h18"/>',lang:'<path d="M4 5h9M8.5 3v2M6 5c1 4 4 7 7 8M12 5c-1 4-4 7-8 9M14 21l4-10 4 10M15.5 18h5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5L19 19M5 19l1.5-1.5M17.5 6.5L19 5"/>',moon:'<path d="M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10z"/>',star:'<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="M15.5 8.5L13.5 13.5 8.5 15.5 10.5 10.5z"/>',repeat:'<path d="M17 3l3 3-3 3M4 11V9a3 3 0 0 1 3-3h13M7 21l-3-3 3-3M20 13v2a3 3 0 0 1-3 3H4"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',doc:'<path d="M6 3h9l4 4v14H6zM9 12h7M9 16h7"/>',check:'<path d="M5 12l5 5 9-10"/>'};
const I=(n,s=20)=>`<svg class="i" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${D[n]||''}</svg>`;
const SI={Matemática:'calc',Português:'book',História:'bank',Geografia:'globe',Biologia:'leaf',Física:'atom',Química:'flask',Inglês:'lang'},ic=(n,s)=>I(SI[n]||'book',s);
let form=0,range='semana',ttab='hoje',rtab='pend',fm={s:'',t:''};window.dsel=25;
const TH=()=>localStorage['studyflow.theme']||'dark';document.documentElement.dataset.theme=TH();
const theme=()=>{const t=TH()=='dark'?'light':'dark';localStorage['studyflow.theme']=t;document.documentElement.dataset.theme=t;render()};
const ib=(i,fn,l)=>`<button class="ib" aria-label="${l}" onclick="${fn}">${I(i,19)}</button>`,hd=(t,l='',r='')=>`<div class="top"><div class="sl">${l}</div><h1>${t}</h1><div class="sr">${r}</div></div>`,ht=t=>`<p class="hint">${t}</p>`,sq=(i,c='var(--blue)')=>`<span class="sq" style="background:${c}">${i}</span>`;
const dm=d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'}),wd=d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','');
const tmin=m=>m>=60?(m/60|0)+'h'+(m%60?pad(m%60)+'min':''):m+'min';
const taskRow=t=>`<div class="t ${t.done?'d':''}"><input type="checkbox" aria-label="Concluir" ${t.done?'checked':''} onchange="T.toggle('${t.id}')"><div class="grow"><div class="tt">${esc(t.title)}</div><small>${esc(sj(t.subject).name)} · ${tmin(t.min)} · ${t.pr} · ${t.due.slice(8)}/${t.due.slice(5,7)}</small></div><button class="mini" aria-label="Editar" onclick="T.edit('${t.id}')">${I('edit',17)}</button><button class="mini" aria-label="Excluir" onclick="T.del('${t.id}')">${I('x',17)}</button></div>`;
const taskForm=()=>`<form class="card f" onsubmit="event.preventDefault();T.add()"><label>Nome da tarefa</label><input id="tt" placeholder="Ex: Resolver lista de exercícios" required><div class="row"><div class="grow f"><label>Matéria</label><select id="ts">${opts()}</select></div><div class="grow f"><label>Prazo</label><input id="td" type="date" value="${today()}"></div></div><div class="row"><div class="grow f"><label>Tempo estimado (min)</label><input id="tm2" type="number" min="1" value="30"></div><div class="grow f"><label>Prioridade</label><select id="tp"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div></div><button class="p">Adicionar tarefa</button></form>`;
// ---- cálculos
const longest=()=>{const d=[...new Set(S.sessions.map(s=>day(s.startedAt)))].sort();let b=0,c=0,p=null;d.forEach(x=>{c=p&&Math.round((new Date(x)-new Date(p))/864e5)==1?c+1:1;b=Math.max(b,c);p=x});return b};
const rdone=()=>S.reviews.filter(r=>r.done).length,xp=()=>Math.round(dur(()=>1)/60)+rdone()*20,lvl=()=>(xp()/500|0)+1;
const ACH=()=>{const m=dur(()=>1)/60,n=S.sessions.length,tp=new Set(S.sessions.map(s=>s.topic)).size,l=Math.max(longest(),streak());return[['star','Primeiro passo','Conclua 1 sessão de estudo',n,1],['clock','1 hora de foco','Acumule 1h estudada',m,60],['clock','5 horas de foco','Acumule 5h estudadas',m,300],['trophy','10 horas de foco','Acumule 10h estudadas',m,600],['flame','7 dias seguidos','Estude 7 dias em sequência',l,7],['flame','30 dias seguidos','Estude 30 dias em sequência',l,30],['repeat','Primeira revisão','Conclua 1 revisão',rdone(),1],['compass','Explorador','Estude 10 conteúdos diferentes',tp,10],['target','Dedicado','Conclua 20 sessões',n,20]]};
const chartN=n=>{const ds=[...Array(n)].map((_,i)=>add(0,i-n+1)),v=ds.map(d=>dur(s=>day(s.startedAt)==d)/60),m=Math.max(30,...v);return`<div class="chart ${n>7?'th':''}">${ds.map((d,i)=>`<div class="${d==today()?'now':''}"><small>${n==7&&v[i]?Math.round(v[i]):''}</small><b style="height:${v[i]/m*100}px"></b></div>`).join('')}</div><div class="lb">${ds.map((d,i)=>`<span>${n==7?wd(d).slice(0,3):(i%5==0?d.slice(8):'')}</span>`).join('')}</div>`};
// ---- páginas
const P={
home(){const pend=S.tasks.filter(t=>!t.done),hj=pend.filter(t=>t.due<=today()),ex=S.exams.filter(e=>e.date>=today()).sort((a,b)=>a.date>b.date?1:-1),e=ex[0],dl=e?Math.round((new Date(e.date)-new Date(today()))/864e5):0,nr=S.reviews.filter(r=>!r.done&&r.due<=today()).length,a=e?avg(e.subject):null;
return`${hd(`<span class="logo">${I("book",22)}<span>Study<b>Flow</b></span></span>`,ib(TH()=='dark'?'sun':'moon','theme()','Alternar tema claro/escuro'),`${ib('bell',"go('more','rev')",'Revisões')}${nr?`<i class="bd">${nr}</i>`:''}`)}
<div class="c" style="margin-bottom:16px"><div style="font-size:26px;font-weight:700">Olá, ${esc(S.user.name)}!</div><div class="mu">Seu futuro depende do que você faz hoje.</div></div>
<div class="card row" onclick="go('more','prof')">${sq(I('flame',22),'#f2711c')}<div class="grow"><b>${streak()} ${streak()==1?'dia':'dias'} de sequência</b><br><small>${streak()?'Estude hoje para manter a sequência.':'Conclua uma sessão hoje para começar.'}</small></div>${I('chev',18)}</div>
<div class="grid"><div class="card" onclick="go('study')">${sq(I('clock',20),'#2f6bff')}<div class="big">${hm(dur(s=>day(s.startedAt)==today()))}</div><small>estudados hoje</small></div><div class="card" onclick="go('tasks')">${sq(I('tasks',20),'#14a37f')}<div class="big">${pend.length}</div><small>tarefas pendentes</small></div><div class="card" onclick="go('subjects')">${sq(I('doc',20),'#7c5cf0')}<div class="big">${ex.length}</div><small>provas próximas</small></div></div>
<h2>Próxima prova</h2>${ht('A barra mostra sua preparação: a média atual na matéria.')}${e?`<div class="card"><div class="row">${sq(ic(sj(e.subject).name,22),sj(e.subject).color)}<div class="grow"><b>${esc(sj(e.subject).name)}</b><br><small>${dm(e.date)} · ${dl==0?'é hoje':dl==1?'falta 1 dia':'faltam '+dl+' dias'}</small></div><b>${a?Math.round(a*10)+'%':'—'}</b></div><div class="bar"><i style="width:${a?a*10:0}%"></i></div></div>`:'<div class="card c mu">Nenhuma prova. Cadastre em Matérias.</div>'}
<h2>Tarefas de hoje</h2>${ht('Marque a caixa para concluir. Inclui tarefas atrasadas.')}<div class="card">${hj.map(taskRow).join('')||'<div class="c mu">Nada pendente para hoje.</div>'}</div>
<button class="p" onclick="go('timer')">${I('play',18)} Começar a estudar</button>
<h2>Minutos estudados na semana</h2><div class="card">${chartN(7)}</div>
<button class="fab" aria-label="Nova tarefa" onclick="go('tasks');form=1;render(1)">${I('plus',26)}</button>`},
subjects(){return`${hd('Matérias')}${ht('Média = notas com peso. A barra mostra a média de 0 a 10.')}${S.subjects.map(s=>{const a=avg(s.id),n=S.sessions.filter(x=>x.subject==s.id),tp=new Set(n.map(x=>x.topic)).size;return`<div class="card"><div class="row">${sq(ic(s.name,22),s.color)}<div class="grow"><b>${esc(s.name)}</b><br><small>${tp} conteúdos · ${n.length} sessões · ${hm(n.reduce((t,x)=>t+x.duration,0))}</small></div><div class="c"><div class="big">${f1(a)}</div><small>média</small></div></div><div class="bar"><i style="width:${a?a*10:0}%;background:${s.color}"></i></div>${need(s.id)}</div>`}).join('')}
<h2>Cadastrar</h2>${ht('Adicione matérias, notas e provas.')}<form class="card row" onsubmit="event.preventDefault();addSub()"><input id="sn" placeholder="Nome da nova matéria" required><button class="p" style="width:auto;padding:12px 18px" aria-label="Adicionar">${I('plus',18)}</button></form>
<form class="card f" onsubmit="event.preventDefault();addGrade()"><b>Nova nota</b><select id="gs">${opts()}</select><input id="gn" placeholder="Avaliação (ex: Prova 1)" required><div class="row"><input id="gv" type="number" step="0.1" min="0" max="10" placeholder="Nota (0 a 10)" required><input id="gw" type="number" step="0.5" min="0.5" value="1" aria-label="Peso"></div><small>Segundo campo = peso da avaliação.</small><button class="p">Salvar nota</button></form>
<form class="card f" onsubmit="event.preventDefault();addExam()"><b>Nova prova</b><div class="row"><select id="es">${opts()}</select><input id="ed" type="date" required></div><button class="p">Salvar prova</button></form>`},
tasks(){const p=S.tasks.filter(t=>!t.done),h=today(),L={hoje:p.filter(t=>t.due<=h),semana:p.filter(t=>t.due<=add(0,7)),todas:S.tasks},prox=p.filter(t=>t.due>h);
return`${hd('Tarefas','',ib('plus','form=!form;render(1)','Nova tarefa'))}${form?taskForm():''}<div class="tabs">${[['hoje','Hoje'],['semana','Semana'],['todas','Todas']].map(([k,l])=>`<button class="${ttab==k?'on':''}" onclick="ttab='${k}';render(1)">${l} (${L[k].length})</button>`).join('')}</div><div class="card">${L[ttab].map(taskRow).join('')||'<div class="c mu">Nenhuma tarefa aqui.</div>'}</div>${ttab=='hoje'&&prox.length?`<h2>Próximas tarefas</h2><div class="card">${prox.slice(0,4).map(taskRow).join('')}</div>`:''}`},
study(){const a=S.active,n={hoje:1,semana:7,mes:30}[range],ds=[...Array(n)].map((_,i)=>add(0,-i)),pv=[...Array(n)].map((_,i)=>add(0,-i-n)),rs=S.sessions.filter(s=>ds.includes(day(s.startedAt))),tot=rs.reduce((t,s)=>t+s.duration,0),dd=tot-dur(s=>pv.includes(day(s.startedAt))),by={};
rs.forEach(s=>by[day(s.startedAt)]=(by[day(s.startedAt)]||0)+s.duration);const best=Object.entries(by).sort((x,y)=>y[1]-x[1])[0],bs=S.subjects.map(s=>[s,rs.filter(x=>x.subject==s.id).reduce((t,x)=>t+x.duration,0)]).filter(x=>x[1]).sort((x,y)=>y[1]-x[1]),mx=rs.reduce((m,s)=>Math.max(m,s.duration),0);
const mc=(l,v,h)=>`<div class="card"><small>${l}</small><div class="big" style="font-size:18px">${v}</div><small>${h}</small></div>`;
return`${hd('Estatísticas')}${ht('Só conta o tempo em que o cronômetro esteve ativo.')}${a?`<div class="card row" onclick="go('timer')">${sq(I('clock',20))}<b class="grow">Sessão em andamento</b>${I('chev',18)}</div>`:`<button class="p" onclick="go('timer')">${I('play',18)} Iniciar sessão de estudo</button>`}
<div class="tabs" style="margin-top:16px">${[['hoje','Hoje'],['semana','Semana'],['mes','Mês']].map(([k,l])=>`<button class="${range==k?'on':''}" onclick="range='${k}';render(1)">${l}</button>`).join('')}</div>
<div class="card c"><small>Tempo total ${range=='hoje'?'hoje':range=='semana'?'nos últimos 7 dias':'nos últimos 30 dias'}</small><div class="big xl">${hm(tot)}</div><small>${dd>=0?'+':'−'}${hm(Math.abs(dd))} em relação ao período anterior</small>${chartN(range=='mes'?30:7)}</div>
<div class="grid g2">${mc('Média por dia',hm(tot/n),'total ÷ dias do período')}${mc('Melhor dia',best?wd(best[0])+' · '+hm(best[1]):'—','dia com mais estudo')}${mc('Matéria mais estudada',bs[0]?esc(bs[0][0].name):'—',bs[0]?hm(bs[0][1]):'sem sessões')}${mc('Sessões',rs.length,'no período')}${mc('Duração média',rs.length?hm(tot/rs.length):'—','por sessão')}${mc('Maior sessão',mx?hm(mx):'—','no período')}</div>
<div class="card"><b>Tempo por matéria</b>${bs.map(([s,v])=>`<div style="margin-top:14px"><div class="row"><span style="width:12px;height:12px;border-radius:4px;background:${s.color}"></span><span class="grow">${esc(s.name)}</span><small>${hm(v)} · ${Math.round(v/tot*100)}%</small></div><div class="bar" style="margin-top:6px"><i style="width:${v/tot*100}%;background:${s.color}"></i></div></div>`).join('')||'<p class="mu c" style="margin-top:8px">Nenhuma sessão neste período.</p>'}</div>`},
timer(){const a=S.active;
if(done)return`${hd('Estudo concluído')}<div class="card c">${sq(I('check',24),'var(--ok)').replace('class="sq"','class="sq" style="margin:0 auto 10px"')}<b>${esc(sj(done.subject).name)}</b><br><span class="mu">${esc(done.topic)} · ${hm(done.duration)} estudados</span><h2>Como você se sente sobre esse conteúdo?</h2>${ht('A resposta define quando você vai revisar.')}${[['Não entendi','amanhã'],['Entendi pouco','em 2 dias'],['Entendi razoavelmente','em 4 dias'],['Entendi bem','em 7 dias'],['Dominei','em 14 dias']].map(([t,d],i)=>`<button class="g" style="border:1px solid var(--line)" onclick="rate(${i+1})">${t} <small>· revisar ${d}</small></button>`).join('')}</div>`;
const run=a&&running(a),pl=a?a.planned:(+dsel||25)*60,left=a?pl-elapsed(a):pl,C=2*Math.PI*78,pr=a?Math.min(1,elapsed(a)/pl):0;
const ring=`<svg class="ring" width="210" height="210" viewBox="0 0 200 200"><circle cx="100" cy="100" r="78" fill="none" stroke="var(--soft)" stroke-width="9"/><circle id="rg" cx="100" cy="100" r="78" fill="none" stroke="var(--blue)" stroke-width="9" stroke-linecap="round" stroke-dasharray="${C}" stroke-dashoffset="${C*pr}" transform="rotate(-90 100 100)"/><text x="100" y="106" text-anchor="middle" class="tm ${run?'run':''}" id="tm">${fmt(left)}</text><text x="100" y="130" text-anchor="middle" class="sb">${a?(run?'Tempo restante':'Pausado'):'Duração do foco'}</text></svg>`;
if(a)return`${hd('Modo foco','',ib('back',"go('study')",'Voltar'))}${a.recover?`<div class="card c">Sessão interrompida (aba fechada). Contamos apenas até ${new Date(a.seen).toLocaleTimeString('pt-BR')}.<button class="p" style="margin-top:12px" onclick="S.active.recover=0;pause()">Recuperar e continuar</button><button class="g" onclick="finish()">Encerrar e salvar</button></div>`:''}
<div class="c"><div class="row" style="justify-content:center">${sq(ic(sj(a.subject).name,22),sj(a.subject).color)}<div style="text-align:left"><b>${esc(sj(a.subject).name)}</b><br><small>${esc(a.topic)}</small></div></div></div>${ring}<p class="hint">Sessão nº ${S.sessions.length+1} · meta ${Math.round(pl/60)} min · pausas não contam</p>
${a.recover?'':`<button class="p" onclick="pause()">${run?I('pause',18)+' Pausar':I('play',18)+' Continuar'}</button><button class="g" style="border:1px solid var(--line)" onclick="finish()">Finalizar e salvar</button><button class="g" onclick="finish(1)">Cancelar sessão</button>`}`;
return`${hd('Iniciar estudo','',ib('back',"go('study')",'Voltar'))}${ht('Escolha o que vai estudar e por quanto tempo.')}<div class="card f"><label>Matéria</label><select id="ss">${opts(fm.s)}</select><label>Conteúdo</label><input id="st" placeholder="Ex: Equações do 2º grau" value="${esc(fm.t)}"><label>Duração (minutos)</label><div class="chips">${[15,25,45,60].map(m=>`<button class="${dsel==m?'on':''}" onclick="setD(${m})">${m}</button>`).join('')}<button class="${[15,25,45,60].includes(+dsel)?'':'on'}" onclick="setD(+prompt('Minutos:','30')||25)">${[15,25,45,60].includes(+dsel)?'Outro':dsel}</button></div></div>${ring}<button class="p" onclick="startS()">${I('play',18)} Começar estudo</button>`},
more(){const rv=S.reviews.filter(r=>(rtab=='pend')!=r.done).sort((x,y)=>x.due>y.due?1:-1);
if(sub=='tutor')return`${hd('Tutor','',ib('back',"go('more')",'Voltar'))}<div class="msg">Olá, ${esc(S.user.name)}! Diga o que você quer aprender hoje. Posso explicar, criar exercícios, resumir e ajudar na revisão.</div>${chat.map(m=>`<div class="msg ${m.u?'u':''}">${esc(m.t)}</div>`).join('')}<div style="margin:16px 0">${[['book','Explicar conteúdo'],['tasks','Criar exercícios'],['doc','Fazer resumo'],['repeat','Revisar assunto'],['trophy','Simulado']].map(([i,b])=>`<button class="qb" onclick="$('#ti').value='${b}: ';$('#ti').focus()">${I(i,19)} ${b}</button>`).join('')}</div><form class="row" onsubmit="event.preventDefault();ask()"><input id="ti" placeholder="Digite sua dúvida aqui..."><button class="ib" aria-label="Enviar">${I('send',18)}</button></form>`;
if(sub=='rev')return`${hd('Revisões','',ib('back',"go('more')",'Voltar'))}${ht('Criadas automaticamente quando você termina uma sessão.')}<div class="tabs">${[['pend','Pendentes'],['conc','Concluídas']].map(([k,l])=>`<button class="${rtab==k?'on':''}" onclick="rtab='${k}';render(1)">${l}</button>`).join('')}</div><div class="card">${rv.map(r=>`<div class="t"><div class="grow">${esc(r.topic)}<br><small>${r.due<=today()?'Hoje':dm(r.due)} · ${esc(sj(r.subject).name)}</small></div><button class="mini" aria-label="${rtab=='pend'?'Concluir':'Reabrir'}" onclick="S.reviews.find(x=>x.id=='${r.id}').done=${rtab=='pend'};save();render(1)">${I(rtab=='pend'?'check':'repeat',20)}</button></div>`).join('')||'<div class="c mu">Nada por aqui.</div>'}</div><p class="hint">Você já revisou ${rdone()} assuntos.</p>`;
if(sub=='prof')return`${hd('Meu progresso','',ib('back',"go('more')",'Voltar'))}<div class="card"><div class="row">${sq(I('user',28),'var(--blue)').replace('42px','')}<div class="grow"><b style="font-size:19px">Nível ${lvl()}</b><div class="bar" style="margin-top:6px"><i style="width:${xp()%500/5}%"></i></div><small>${xp()%500} / 500 XP</small></div></div><p class="hint" style="margin:10px 0 0">1 min estudado = 1 XP · revisão concluída = 20 XP</p></div><div class="card"><small>Seu nome</small><input value="${esc(S.user.name)}" onchange="S.user.name=this.value.trim()||'Dudu';save()"></div>
<div class="grid g2"><div class="card"><div class="big">${streak()}</div><small>dias seguidos</small></div><div class="card"><div class="big">${Math.max(longest(),streak())}</div><small>melhor sequência</small></div><div class="card"><div class="big">${hm(dur(()=>1))}</div><small>total estudado</small></div><div class="card"><div class="big">${S.sessions.length}</div><small>sessões</small></div></div><h2>Conquistas</h2>${ht('Cada conquista é desbloqueada com seus registros reais.')}<div class="grid g2">${ACH().map(([i,n,d,v,t])=>`<div class="card ach ${v>=t?'':'off'}">${sq(I(i,24)).replace('class="sq"','class="sq"')}<b>${n}</b><small>${d}</small><div class="bar"><i style="width:${Math.min(100,v/t*100)}%"></i></div><small>${Math.min(Math.round(v),t)}/${t}${v>=t?' · concluída':''}</small></div>`).join('')}</div>`;
return`${hd('Mais')}${[['rev','brain','Revisões','Conteúdos para rever hoje'],['prof','trophy','Progresso e conquistas','Nível, sequência e medalhas'],['tutor','bot','Tutor com IA','Tire dúvidas e crie exercícios']].map(([k,i,l,d])=>`<div class="card row" onclick="go('more','${k}')">${sq(I(i,22))}<div class="grow"><b>${l}</b><br><small>${d}</small></div>${I('chev',18)}</div>`).join('')}<div class="card row" onclick="theme()">${sq(I(TH()=='dark'?'sun':'moon',22),'#7c5cf0')}<div class="grow"><b>Tema ${TH()=='dark'?'claro':'escuro'}</b><br><small>Alternar aparência do app</small></div>${I('chev',18)}</div><h2>Dados</h2>${ht('Tudo fica salvo neste aparelho.')}<button class="g" style="border:1px solid var(--line)" onclick="if(confirm('Apagar tudo e começar do zero?')){S=empty();save();go('home')}">Apagar dados de demonstração</button><button class="g" onclick="if(confirm('Restaurar demonstração?')){S=demo();save();go('home')}">Restaurar demonstração</button>`}};
function need(id){const g=S.grades.filter(g=>g.subject==id);if(!g.length)return'';const W=g.reduce((t,x)=>t+x.w,0),sum=g.reduce((t,x)=>t+x.v*x.w,0),n=8*(W+1)-sum;return`<small class="mu" style="display:block;margin-top:8px">${n<=0?'Você já garante média 8,0.':n>10?'Média 8,0 já não é possível só com a próxima prova.':'Para fechar com 8,0, tire ~'+f1(n)+' na próxima avaliação (peso 1).'}</small>`}
const addSub=()=>{const c=['#2f6bff','#c24bd6','#f5a623','#19b6c9','#22c58b','#ef4b5b','#8b5cf6','#ec7a3c'];S.subjects.push({id:uid(),name:$('#sn').value.trim(),color:c[S.subjects.length%8]});save();render(1)},addGrade=()=>{S.grades.push({id:uid(),subject:$('#gs').value,name:$('#gn').value,v:+$('#gv').value,w:+$('#gw').value||1});save();render(1)},addExam=()=>{S.exams.push({id:uid(),subject:$('#es').value,date:$('#ed').value});save();render(1)};
const setD=m=>{fm={s:$('#ss').value,t:$('#st').value};window.dsel=m;render(1)};
async function askAI(msg){return null}
async function ask(){const t=$('#ti').value.trim();if(!t)return;chat.push({u:1,t});const r=await askAI(t);chat.push({u:0,t:r||'IA ainda não configurada. Conecte uma API na função askAI() do arquivo app.js.'});render(1)}
const go=(p,sb='')=>{page=p;sub=sb;form=0;ttab='hoje';rtab='pend';range='semana';fm={s:'',t:''};if(p!='timer')done=null;scrollTo(0,0);render(0)};
function render(keep){const items=[['home','home','Início'],['subjects','book','Matérias'],['tasks','tasks','Tarefas'],['study','chart','Estudos'],['more','more','Mais']],cur=page=='timer'?'study':page;
$('#nav').innerHTML=items.map(([k,i,l])=>`<a class="${cur==k?'on':''}" onclick="go('${k}')">${I(i,22)}${l}</a>`).join('');const el=$('#app');el.className=keep?'na':'';el.innerHTML=P[page]()}
render();
