// ===================== CONFIGURAÇÃO =====================
// Se o site está no GitHub Pages, o servidor (login, nuvem e tutor) fica em outro lugar.
// Coloque aqui o endereço do seu servidor no Render, sem barra no final.
// Exemplo: const API_URL='https://studyflow.onrender.com';
// Se o site e o servidor estão no mesmo endereço (Render), deixe vazio.
const API_URL='';
// ========================================================

const K='studyflow.v1',$=s=>document.querySelector(s),uid=()=>Math.random().toString(36).slice(2,9),
day=t=>new Date(t).toLocaleDateString('sv'),pad=n=>String(n).padStart(2,'0'),
fmt=s=>{s=Math.max(0,Math.round(s));return pad(s/60|0)+':'+pad(s%60)},
hm=s=>{const m=Math.round(s/60);return m>=60?(m/60|0)+'h'+pad(m%60)+'min':m+'min'},
esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),
add=(d,n)=>day(Date.now()+n*864e5),today=()=>day(Date.now());
const PAL=['#4F8CFF','#A66BFF','#FF9F43','#1FC4D6','#2FCB8E','#FF5C7A','#7C83FF','#FF7A59'];
let rvf='more',S,page='home',sub='',done=null,chat=[],ttab='d3',rtab='pend',range='semana',fm={s:'',t:''},dsel=25,showRF=0;

// ---------- dados ----------
function demo(){const m=['Matemática','Português','História','Geografia','Biologia','Física','Química','Inglês'].map((name,i)=>({id:uid(),name,color:PAL[i]}));
const id=n=>m.find(x=>x.name==n).id,ses=[];
[[0,'Matemática',1500],[0,'História',1200],[1,'Biologia',1800],[2,'Matemática',2400],[3,'Português',1500],[4,'Física',1200],[5,'Matemática',3000],[6,'Química',1500]].forEach(([d,n,s])=>{const t=Date.now()-d*864e5-36e5;ses.push({id:uid(),subject:id(n),topic:'Revisão',startedAt:t,endedAt:t+s*1e3,duration:s,status:'completed'})});
return{pal:3,user:{name:'Dudu',year:'',school:''},subjects:m,tasks:[['Revisar matemática','Matemática',0,40,'Alta'],['Fazer trabalho de história','História',1,90,'Média'],['Estudar biologia','Biologia',2,30,'Média'],['Ler capítulo de português','Português',3,40,'Baixa'],['Redação','Português',6,60,'Média']].map(([title,s,d,min,pr])=>({id:uid(),title,subject:id(s),due:add(0,d),min,pr,done:false})),
grades:[['Matemática','Prova 1',8.5],['Matemática','Trabalho',7.5],['Português','Prova 1',7.8],['História','Prova 1',9],['Biologia','Prova 1',8.2]].map(([s,name,v])=>({id:uid(),subject:id(s),name,v})),
exams:[{id:uid(),subject:id('Matemática'),date:add(0,8)},{id:uid(),subject:id('Física'),date:add(0,15)}],sessions:ses,reviews:[['Revolução Industrial','História',0],['Equações do 2º grau','Matemática',1],['Célula eucarionte','Biologia',3]].map(([topic,s,d])=>({id:uid(),topic,subject:id(s),due:add(0,d),done:false})),active:null}}
const empty=()=>({pal:3,user:{name:'Dudu',year:'',school:''},subjects:[],tasks:[],grades:[],exams:[],sessions:[],reviews:[],active:null});
// garante os campos e aplica as cores novas das matérias (uma vez)
const fix=()=>{S.user=S.user||{name:'Dudu'};['subjects','tasks','grades','exams','sessions','reviews'].forEach(k=>S[k]=S[k]||[]);if(S.pal!=3){S.subjects.forEach((s,i)=>s.color=PAL[i%PAL.length]);S.pal=3}};
try{S=JSON.parse(localStorage[K])}catch(e){}S=S||demo();fix();
const save=()=>{S.updatedAt=Date.now();localStorage[K]=JSON.stringify(S);push()},sj=id=>S.subjects.find(s=>s.id==id)||{name:'—',color:'#bbb'};
const opts=sel=>S.subjects.map(s=>`<option value="${s.id}" ${s.id==sel?'selected':''}>${esc(s.name)}</option>`).join('');

// ---------- cronômetro: tempo real = soma dos trechos [início, fim] ----------
const elapsed=a=>a.segs.reduce((t,[s,e])=>t+((e??Date.now())-s),0)/1e3,running=a=>a&&a.segs.at(-1)[1]==null;
function startS(){const subject=$('#ss').value,topic=$('#st').value.trim()||'Estudo livre',min=+dsel||25;if(!subject)return alert('Crie uma matéria primeiro.');
S.active={subject,topic,planned:min*60,startedAt:Date.now(),segs:[[Date.now(),null]],seen:Date.now()};page='timer';save();render()}
function pause(){const a=S.active;if(running(a))a.segs.at(-1)[1]=Date.now();else a.segs.push([Date.now(),null]);save();render(1)}
function finish(cancel){const a=S.active;if(!a)return;if(running(a))a.segs.at(-1)[1]=Date.now();S.active=null;
if(cancel||elapsed(a)<5){save();return go('study')}
const r={id:uid(),subject:a.subject,topic:a.topic,startedAt:a.startedAt,endedAt:a.segs.at(-1)[1],duration:Math.round(elapsed(a)),status:'completed'};S.sessions.push(r);done=r;page='timer';save();render()}
function rate(n){const d=[1,2,4,7,14][n-1];S.reviews.push({id:uid(),topic:done.topic,subject:done.subject,due:add(0,d),done:false});done=null;save();go('study')}
setInterval(()=>{const a=S.active;if(!a)return;if(running(a)){a.seen=Date.now();localStorage[K]=JSON.stringify(S);if(elapsed(a)>=a.planned)return finish()}const t=$('#tm');if(t){t.textContent=fmt(a.planned-elapsed(a));const g=$('#rg'),C=2*Math.PI*78;if(g)g.setAttribute('stroke-dashoffset',C*Math.min(1,elapsed(a)/a.planned))}},1000);

// ---------- métricas ----------
const dur=f=>S.sessions.filter(f).reduce((t,s)=>t+s.duration,0);
function streak(){let n=0,i=0;const ds=new Set(S.sessions.map(s=>day(s.startedAt)));if(!ds.has(add(0,0)))i=-1;while(ds.has(add(0,i-n)))n++;return n}
const longest=()=>{const d=[...new Set(S.sessions.map(s=>day(s.startedAt)))].sort();let b=0,c=0,p=null;d.forEach(x=>{c=p&&Math.round((new Date(x)-new Date(p))/864e5)==1?c+1:1;b=Math.max(b,c);p=x});return b};
function avg(id){const g=S.grades.filter(g=>g.subject==id);return g.length?g.reduce((t,x)=>t+x.v,0)/g.length:null}
// notas: a média é sempre arredondada PARA BAIXO (5,95 vira 5,9). A nota que falta tirar arredonda PARA CIMA, para não prometer o que não fecha a conta.
const fl=v=>Math.floor(v*10+1e-9)/10,ce=v=>Math.ceil(v*10-1e-9)/10,vir=v=>v.toFixed(1).replace('.',','),
f1=v=>v==null?'—':vir(fl(v)),fc=v=>vir(ce(v)),r2=v=>String(Math.round(v*100)/100).replace('.',',');
const rdone=()=>S.reviews.filter(r=>r.done).length,xp=()=>Math.round(dur(()=>1)/60)+rdone()*20,lvl=()=>(xp()/500|0)+1,dueRev=()=>S.reviews.filter(r=>!r.done&&r.due<=today()).length;
const ACH=()=>{const m=dur(()=>1)/60,n=S.sessions.length,tp=new Set(S.sessions.map(s=>s.topic)).size,l=Math.max(longest(),streak());return[['star','Primeiro passo','Conclua 1 sessão de estudo',n,1],['clock','1 hora de foco','Acumule 1h estudada',m,60],['clock','5 horas de foco','Acumule 5h estudadas',m,300],['trophy','10 horas de foco','Acumule 10h estudadas',m,600],['flame','7 dias seguidos','Estude 7 dias em sequência',l,7],['flame','30 dias seguidos','Estude 30 dias em sequência',l,30],['repeat','Primeira revisão','Conclua 1 revisão',rdone(),1],['compass','Explorador','Estude 10 conteúdos diferentes',tp,10],['target','Dedicado','Conclua 20 sessões',n,20]]};

// ---------- ícones ----------
const D={more:'<circle cx="5" cy="12" r="1.6"/><circle cx="12" cy="12" r="1.6"/><circle cx="19" cy="12" r="1.6"/>',home:'<path d="M3 11l9-8 9 8"/><path d="M5 10v10h14V10"/>',book:'<path d="M4 19V5a2 2 0 0 1 2-2h13v14H6a2 2 0 0 0-2 2zM4 19a2 2 0 0 0 2 2h13"/>',tasks:'<rect x="4" y="3" width="16" height="18" rx="3"/><path d="M9 12l2 2 4-4"/>',chart:'<path d="M5 20V10M12 20V4M19 20v-7"/>',bell:'<path d="M6 16v-5a6 6 0 0 1 12 0v5l2 2H4z"/><path d="M10 21h4"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',clock:'<circle cx="12" cy="13" r="8"/><path d="M12 9v4l3 2M9 2h6"/>',flame:'<path d="M12 3c1 4 5 5 5 10a5 5 0 0 1-10 0c0-2 1-3 2-4 0 2 1 3 2 3 0-3-1-5 1-9z"/>',plus:'<path d="M12 5v14M5 12h14"/>',edit:'<path d="M4 20h4L19 9l-4-4L4 16z"/>',x:'<path d="M6 6l12 12M18 6L6 18"/>',back:'<path d="M15 5l-7 7 7 7"/>',chev:'<path d="M9 5l7 7-7 7"/>',send:'<path d="M3 11l18-8-8 18-2-8z"/>',play:'<path d="M7 4l13 8-13 8z"/>',pause:'<path d="M8 5v14M16 5v14"/>',bot:'<rect x="4" y="8" width="16" height="12" rx="3"/><path d="M12 4v4M9 14h.01M15 14h.01"/>',trophy:'<path d="M8 4h8v6a4 4 0 0 1-8 0zM8 6H4v2a3 3 0 0 0 4 3M16 6h4v2a3 3 0 0 1-4 3M12 14v4M8 21h8"/>',calc:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6M9 12h.01M12 12h.01M15 12h.01M9 16h.01M12 16h.01M15 16h.01"/>',globe:'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 3 15 0 18M12 3c-3 3-3 15 0 18"/>',flask:'<path d="M9 3h6M10 3v6l-5 10a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-10V3"/>',atom:'<circle cx="12" cy="12" r="1.5"/><ellipse cx="12" cy="12" rx="10" ry="4"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)"/>',leaf:'<path d="M5 19c0-9 5-14 15-14 0 10-5 15-14 15zM5 19l8-8"/>',bank:'<path d="M3 9l9-6 9 6M5 9v9M10 9v9M14 9v9M19 9v9M3 21h18"/>',lang:'<path d="M4 5h9M8.5 3v2M6 5c1 4 4 7 7 8M12 5c-1 4-4 7-8 9M14 21l4-10 4 10M15.5 18h5"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5L19 19M5 19l1.5-1.5M17.5 6.5L19 5"/>',moon:'<path d="M20 14A8 8 0 0 1 10 4a8 8 0 1 0 10 10z"/>',star:'<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>',compass:'<circle cx="12" cy="12" r="9"/><path d="M15.5 8.5L13.5 13.5 8.5 15.5 10.5 10.5z"/>',repeat:'<path d="M17 3l3 3-3 3M4 11V9a3 3 0 0 1 3-3h13M7 21l-3-3 3-3M20 13v2a3 3 0 0 1-3 3H4"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',doc:'<path d="M6 3h9l4 4v14H6zM9 12h7M9 16h7"/>',check:'<path d="M5 12l5 5 9-10"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.7.4-1 .9-1 1.7M12 17h.01"/>',layers:'<path d="M12 3l9 5-9 5-9-5zM3 13l9 5 9-5"/>',cloud:'<path d="M7 18a4 4 0 0 1-.5-8A6 6 0 0 1 18 9.5 4 4 0 0 1 17.5 18z"/>'};
const I=(n,s=20)=>`<svg class="i" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${D[n]||''}</svg>`;
const SI={Matemática:'calc',Português:'book',História:'bank',Geografia:'globe',Biologia:'leaf',Física:'atom',Química:'flask',Inglês:'lang'},ic=(n,s)=>I(SI[n]||'book',s);

// ---------- tema ----------
const TH=()=>localStorage['sf.theme']||'dark';
const paintTheme=()=>{document.documentElement.dataset.theme=TH();const m=document.querySelector('meta[name=theme-color]');if(m)m.content=TH()=='dark'?'#0B1020':'#F2F5FF'};paintTheme();
const theme=()=>{localStorage['sf.theme']=TH()=='dark'?'light':'dark';paintTheme();render(1)};

// ---------- peças de interface ----------
const ib=(i,fn,l)=>`<button class="circ" aria-label="${l}" onclick="${fn}">${I(i,20)}</button>`,
topbar=(t,back)=>`<div class="top">${ib('back',back,'Voltar')}<h1>${t}</h1><span></span></div>`,
ht=t=>`<p class="hint">${t}</p>`,sq=(i,c='var(--g)')=>`<span class="sq" style="background:${c}">${i}</span>`,
name=()=>(S.user.name||'Dudu').trim()||'Dudu',inicial=()=>esc(name()[0].toUpperCase()),
dm=d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{day:'numeric',month:'long'}),wd=d=>new Date(d+'T12:00').toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),
dd=d=>Math.round((new Date(d+'T12:00')-new Date(today()+'T12:00'))/864e5),
dl=d=>{const n=dd(d);return n<0?'Atrasada':n==0?'Hoje':n==1?'Amanhã':wd(d)+', '+d.slice(8)+'/'+d.slice(5,7)},
tmin=m=>m>=60?(m/60|0)+'h'+(m%60?pad(m%60)+'min':''):m+'min',byDue=(a,b)=>a.due>b.due?1:a.due<b.due?-1:0,
rf=()=>page=='tasks'&&$('#tlist')?tl():render(1);
const taskRow=(t,full)=>`<div class="t ${t.done?'d':''}"><input type="checkbox" aria-label="Concluir tarefa" ${t.done?'checked':''} onchange="T.toggle('${t.id}')"><div class="grow"><div class="tt">${esc(t.title)}</div><div class="meta"><span><i class="dot" style="background:${sj(t.subject).color}"></i>${esc(sj(t.subject).name)}</span><span class="${!t.done&&dd(t.due)<0?'late':''}">${dl(t.due)}</span>${full?`<span>${tmin(t.min)}</span><span>Prioridade ${t.pr.toLowerCase()}</span>`:''}</div></div>${full?`<button class="mini" aria-label="Editar" onclick="T.edit('${t.id}')">${I('edit',17)}</button><button class="mini" aria-label="Excluir" onclick="T.del('${t.id}')">${I('x',17)}</button>`:''}</div>`;

// ---------- tarefas ----------
const T={toggle(id){const t=S.tasks.find(t=>t.id==id);if(!t)return;t.done=!t.done;save();rf()},del(id){S.tasks=S.tasks.filter(t=>t.id!=id);save();rf()},edit(id){const t=S.tasks.find(t=>t.id==id),n=prompt('Editar tarefa:',t.title);if(n&&n.trim()){t.title=n.trim();save();rf()}},
add(){const title=$('#tt').value.trim();if(!title)return;S.tasks.push({id:uid(),title,subject:$('#ts').value,due:$('#td').value||today(),min:+$('#tm2').value||30,pr:$('#tp').value,done:false});save();$('#tt').value='';tl();$('#tt').focus()}};
const tasksList=()=>{const p=S.tasks.filter(t=>!t.done).sort(byDue),lim=add(0,3),L={d3:p.filter(t=>t.due<=lim),all:p,feitas:S.tasks.filter(t=>t.done)},E={d3:'Nada para os próximos 3 dias.',all:'Você não tem tarefas pendentes.',feitas:'Nenhuma tarefa concluída ainda.'};
return`<div class="tabs">${[['d3','Próximos 3 dias'],['all','Todas'],['feitas','Feitas']].map(([k,l])=>`<button class="${ttab==k?'on':''}" onclick="ttab='${k}';tl()">${l} (${L[k].length})</button>`).join('')}</div><div class="card list">${L[ttab].map(t=>taskRow(t,1)).join('')||`<div class="empty">${E[ttab]}</div>`}</div>`};
const tl=()=>{const e=$('#tlist');e?e.innerHTML=tasksList():render(1)};
const taskForm=()=>S.subjects.length?`<form class="card f" onsubmit="event.preventDefault();T.add()"><label for="tt">Nova tarefa</label><input id="tt" placeholder="Ex: Lista de exercícios de física" required><div class="row"><div class="grow f"><label for="ts">Matéria</label><select id="ts">${opts()}</select></div><div class="grow f"><label for="td">Para quando</label><input id="td" type="date" value="${today()}"></div></div><details><summary>Mais detalhes: tempo e prioridade</summary><div class="row"><div class="grow f"><label for="tm2">Minutos</label><input id="tm2" type="number" min="1" value="30"></div><div class="grow f"><label for="tp">Prioridade</label><select id="tp"><option>Alta</option><option selected>Média</option><option>Baixa</option></select></div></div></details><button class="p">${I('plus',18)} Adicionar tarefa</button></form>`:`<div class="card empty">Crie uma matéria primeiro, na aba Matérias.</div>`;

// ---------- matérias ----------
function need(id){const g=S.grades.filter(g=>g.subject==id),t=S.target||8,nt=h=>`<div class="note">${I('target',18)}<span>${h}</span></div>`;if(!g.length)return nt('Cadastre uma nota para ver quanto precisa tirar na próxima prova.');
const n=g.length,sum=g.reduce((a,x)=>a+x.v,0),x=t*(n+1)-sum;
return nt(x<=0?`Você já garante média ${f1(t)}, mesmo que tire 0 na próxima prova.`:x>10?`Só com mais uma prova não dá para chegar em ${f1(t)}. Precisaria de mais avaliações.`:`Para terminar com média ${f1(t)}, tire pelo menos <b>${fc(x)}</b> na próxima prova.<br><small>Conta: (${r2(sum)} + nota) ÷ ${n+1} = ${f1(t)}</small>`)}
const addSub=()=>{const n=$('#sn').value.trim();if(!n)return;S.subjects.push({id:uid(),name:n,color:PAL[S.subjects.length%PAL.length]});save();render(1)},
addGrade=id=>{const v=+String($('#gv').value).replace(',','.');if($('#gv').value.trim()===''||!(v>=0&&v<=10))return alert('Digite uma nota de 0 a 10.');S.grades.push({id:uid(),subject:id,name:$('#gn').value.trim()||'Avaliação',v});save();render(1)},
delG=id=>{S.grades=S.grades.filter(g=>g.id!=id);save();render(1)},addExam=id=>{const d=$('#ed').value;if(!d)return alert('Escolha a data da prova.');S.exams.push({id:uid(),subject:id,date:d});save();render(1)},delE=id=>{S.exams=S.exams.filter(e=>e.id!=id);save();render(1)};
function subDetail(id){const s=S.subjects.find(x=>x.id==id);if(!s){sub='';return P.subjects()}
const a=avg(id),n=S.sessions.filter(x=>x.subject==id),tp=new Set(n.map(x=>x.topic)).size,gs=S.grades.filter(g=>g.subject==id),ex=S.exams.filter(e=>e.subject==id&&e.date>=today()).sort((x,y)=>x.date>y.date?1:-1),tk=S.tasks.filter(t=>t.subject==id&&!t.done).sort(byDue);
return`${topbar(esc(s.name),"go('subjects')")}<div class="strip">${S.subjects.map(x=>`<button class="${x.id==id?'on':''}" onclick="go('subjects','${x.id}')"><i class="dot" style="background:${x.color};margin:0"></i>${esc(x.name)}</button>`).join('')}</div>
<div class="cover" style="--c:${s.color}"><div class="row">${sq(ic(s.name,24),'#fff')}<div class="grow"><b style="font-size:18px">Média em ${esc(s.name)}</b><br><small>${gs.length} ${gs.length==1?'nota':'notas'}</small></div><div class="big xl">${f1(a)}</div></div><div class="bar"><i style="width:${a?fl(a)*10:0}%"></i></div></div>
<div class="card"><h2>Notas</h2>${ht('A média é a soma das notas dividida pela quantidade, sempre arredondada para baixo.')}<div class="chips2">${gs.map(x=>`<span class="chip">${esc(x.name)}: ${f1(x.v)}<b onclick="delG('${x.id}')" role="button" aria-label="Remover nota">${I('x',14)}</b></span>`).join('')||'<small>Nenhuma nota ainda.</small>'}</div>${need(id)}
<form class="f" style="margin-top:14px" onsubmit="event.preventDefault();addGrade('${id}')"><div class="row"><input id="gn" placeholder="Avaliação (ex: Prova 1)" aria-label="Nome da avaliação"><input id="gv" type="text" inputmode="decimal" placeholder="Nota" aria-label="Nota de 0 a 10" style="width:96px" required></div><button class="p">${I('plus',18)} Salvar nota</button></form></div>
<div class="card"><h2>Provas</h2>${ex.length?`<div class="list" style="margin-top:8px">${ex.map(e=>{const n=dd(e.date);return`<div class="t"><div class="grow"><div class="tt">${dm(e.date)}</div><small>${n==0?'É hoje':n==1?'Falta 1 dia':'Faltam '+n+' dias'}</small></div><button class="mini" aria-label="Remover prova" onclick="delE('${e.id}')">${I('x',17)}</button></div>`}).join('')}</div>`:ht('Nenhuma prova marcada.')}
<form class="row" style="margin-top:10px" onsubmit="event.preventDefault();addExam('${id}')"><input id="ed" type="date" aria-label="Data da prova" required><button class="p" style="width:auto;white-space:nowrap">Marcar prova</button></form></div>
<div class="card"><h2>Estudo</h2><div class="grid g3" style="margin:12px 0 0"><div class="card"><div class="big">${tp}</div><small>conteúdos</small></div><div class="card"><div class="big">${n.length}</div><small>sessões</small></div><div class="card"><div class="big" style="font-size:20px">${hm(n.reduce((t,x)=>t+x.duration,0))}</div><small>estudados</small></div></div></div>
<div class="card"><h2>Tarefas pendentes</h2><div class="list" style="margin-top:10px">${tk.map(t=>taskRow(t)).join('')||'<div class="empty">Nenhuma tarefa desta matéria.</div>'}</div></div>`}

// ---------- estatísticas ----------
const chartN=n=>{const ds=[...Array(n)].map((_,i)=>add(0,i-n+1)),v=ds.map(d=>dur(s=>day(s.startedAt)==d)/60),m=Math.max(30,...v);return`<div class="chart ${n>7?'th':''}">${ds.map((d,i)=>`<div class="${d==today()?'now':''}"><small>${n==7&&v[i]?Math.round(v[i]):''}</small><b style="height:${v[i]/m*80}px"></b></div>`).join('')}</div><div class="lb">${ds.map((d,i)=>`<span>${n==7?wd(d).slice(0,3):(i%5==0?d.slice(8):'')}</span>`).join('')}</div>`};

// ---------- revisões ----------
const Rv={toggle(id){const r=S.reviews.find(x=>x.id==id);if(!r)return;r.done=!r.done;save();render(1)},
add(){const topic=$('#rt').value.trim();if(!topic)return;S.reviews.push({id:uid(),topic,subject:$('#rs').value,due:$('#rd').value||today(),done:false});showRF=0;save();render(1)}};

// ---------- páginas ----------
const mrow=(i,l,d,fn,end=I('chev',18))=>`<div class="card menu" onclick="${fn}">${sq(I(i,22))}<div class="grow"><b>${l}</b><br><small>${d}</small></div>${end}</div>`,
themeRow=()=>mrow(TH()=='dark'?'moon':'sun','Modo escuro','Alterne entre claro e escuro','theme()','<span class="sw" role="switch" aria-checked="'+(TH()=='dark')+'"></span>'),
openRev=f=>{rvf=f;go('more','rev')};
const P={
home(){const lim=add(0,3),pend=S.tasks.filter(t=>!t.done&&t.due<=lim).sort(byDue),ex=S.exams.filter(e=>e.date>=today()).sort((a,b)=>a.date>b.date?1:-1)[0],nr=dueRev(),hoje=dur(s=>day(s.startedAt)==today());
return`<div class="head" style="margin-bottom:18px"><div><small>${new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})}</small><h1>Olá, ${esc(name())}</h1></div><div class="acts"><button class="circ" aria-label="Revisões${nr?': '+nr+' para hoje':''}" onclick="openRev('home')">${I('bell',20)}${nr?`<i class="bd">${nr}</i>`:''}</button><button class="circ av" aria-label="Meu perfil" onclick="go('profile')">${inicial()}</button></div></div>
<div class="card hero"><div><div class="hl">Hora de estudar?</div><p style="margin-top:4px">Escolha a matéria, o tempo e ligue o cronômetro.</p></div><button class="p" onclick="go('timer')">${I('play',18)} Começar a estudar</button><small>${hoje?'Hoje você já estudou '+hm(hoje)+'.':'Você ainda não estudou hoje.'}</small></div>
<div class="sec"><h2>Tarefas dos próximos 3 dias</h2><a onclick="go('tasks')">Ver todas</a></div>${ht('As atrasadas também aparecem aqui. Marque a caixa quando terminar.')}
<div class="card list">${pend.map(t=>taskRow(t)).join('')||'<div class="empty">Nenhuma tarefa por enquanto.</div>'}</div>
${ex?`<div class="sec"><h2>Próxima prova</h2></div><div class="card row" style="margin-top:8px" onclick="go('subjects','${ex.subject}')">${sq(ic(sj(ex.subject).name,22),sj(ex.subject).color)}<div class="grow"><b>${esc(sj(ex.subject).name)}</b><br><small>${dm(ex.date)}, ${dd(ex.date)==0?'é hoje':dd(ex.date)==1?'falta 1 dia':'faltam '+dd(ex.date)+' dias'}</small></div>${I('chev',18)}</div>`:''}`},
subjects(){if(sub)return subDetail(sub);
return`<div class="head"><h1>Matérias</h1></div>${ht('Toque em uma matéria para ver notas, provas, estudo e tarefas dela.')}
<div class="tiles">${S.subjects.map(s=>{const a=avg(s.id);return`<button class="tile" style="--c:${s.color}" onclick="go('subjects','${s.id}')"><span style="display:flex">${ic(s.name,22)}</span><b>${esc(s.name)}</b><span class="big">${f1(a)}</span><div class="bar"><i style="width:${a?fl(a)*10:0}%"></i></div></button>`}).join('')}</div>
<div class="card row">${sq(I('target',20))}<div class="grow"><b>Média que você quer</b><br><small>Usada para calcular a nota necessária</small></div><input type="number" step="0.5" min="1" max="10" value="${S.target||8}" aria-label="Média desejada" style="width:84px;text-align:center" onchange="S.target=+this.value||8;save();render(1)"></div>
<form class="card row" onsubmit="event.preventDefault();addSub()"><input id="sn" placeholder="Nome da nova matéria" aria-label="Nome da nova matéria" required><button class="p" style="width:auto" aria-label="Adicionar matéria">${I('plus',18)}</button></form>`},
tasks(){return`<div class="head"><h1>Tarefas</h1></div>${ht('Adicione aqui o que precisa fazer. Elas aparecem na tela inicial quando faltarem 3 dias ou menos.')}${taskForm()}<div id="tlist">${tasksList()}</div>`},
study(){const a=S.active,n={hoje:1,semana:7,mes:30}[range],ds=[...Array(n)].map((_,i)=>add(0,-i)),pv=[...Array(n)].map((_,i)=>add(0,-i-n)),rs=S.sessions.filter(s=>ds.includes(day(s.startedAt))),tot=rs.reduce((t,s)=>t+s.duration,0),dif=tot-dur(s=>pv.includes(day(s.startedAt))),by={};
rs.forEach(s=>by[day(s.startedAt)]=(by[day(s.startedAt)]||0)+s.duration);const best=Object.entries(by).sort((x,y)=>y[1]-x[1])[0],bs=S.subjects.map(s=>[s,rs.filter(x=>x.subject==s.id).reduce((t,x)=>t+x.duration,0)]).filter(x=>x[1]).sort((x,y)=>y[1]-x[1]),mx=rs.reduce((m,s)=>Math.max(m,s.duration),0),sk=streak();
const mc=(l,v,h)=>`<div class="card"><small>${l}</small><div class="big" style="font-size:20px">${v}</div><small>${h}</small></div>`;
return`<div class="head"><h1>Estudos</h1></div>
<div class="card row">${sq(I('flame',22),'var(--g)')}<div class="grow"><div class="big">${sk} ${sk==1?'dia':'dias'} seguidos</div><small>${sk?'Estude hoje para manter a sequência.':'Conclua uma sessão hoje para começar.'}</small></div><div class="c"><b>${Math.max(longest(),sk)}</b><br><small>recorde</small></div></div>
${a?`<div class="card row" onclick="go('timer')">${sq(I('clock',20))}<b class="grow">Sessão em andamento</b>${I('chev',18)}</div>`:`<button class="p" style="margin-bottom:18px" onclick="go('timer')">${I('play',18)} Iniciar sessão de estudo</button>`}
${ht('Só conta o tempo em que o cronômetro esteve ativo.')}<div class="tabs">${[['hoje','Hoje'],['semana','Semana'],['mes','Mês']].map(([k,l])=>`<button class="${range==k?'on':''}" onclick="range='${k}';render(1)">${l}</button>`).join('')}</div>
<div class="card c"><small>Tempo total ${range=='hoje'?'hoje':range=='semana'?'nos últimos 7 dias':'nos últimos 30 dias'}</small><div class="big xl">${hm(tot)}</div><small>${dif>=0?'+':'−'}${hm(Math.abs(dif))} em relação ao período anterior</small>${chartN(range=='mes'?30:7)}</div>
<div class="grid">${mc('Média por dia',hm(tot/n),'total ÷ dias do período')}${mc('Melhor dia',best?wd(best[0])+', '+hm(best[1]):'—','dia com mais estudo')}${mc('Mais estudada',bs[0]?esc(bs[0][0].name):'—',bs[0]?hm(bs[0][1]):'sem sessões')}${mc('Sessões',rs.length,'no período')}${mc('Duração média',rs.length?hm(tot/rs.length):'—','por sessão')}${mc('Maior sessão',mx?hm(mx):'—','no período')}</div>
<div class="card"><h2>Tempo por matéria</h2>${bs.map(([s,v])=>`<div style="margin-top:14px"><div class="row"><i class="dot" style="background:${s.color};margin:0"></i><span class="grow">${esc(s.name)}</span><small>${hm(v)}, ${Math.round(v/tot*100)}%</small></div><div class="bar" style="margin-top:6px"><i style="width:${v/tot*100}%;background:${s.color}"></i></div></div>`).join('')||'<p class="empty">Nenhuma sessão neste período.</p>'}</div>`},
timer(){const a=S.active;
if(done)return`${topbar('Estudo concluído',"go('study')")}<div class="card c">${sq(I('check',24),'var(--g)').replace('class="sq"','class="sq" style="margin:0 auto 10px;background:var(--hl)"')}<b>${esc(sj(done.subject).name)}</b><br><span class="mu">${esc(done.topic)}, ${hm(done.duration)} estudados</span><h2 style="margin-top:18px">Quanto você entendeu desse conteúdo?</h2>${ht('A resposta define quando o app vai te lembrar de revisar.')}${[['Não entendi','amanhã'],['Entendi pouco','em 2 dias'],['Entendi razoavelmente','em 4 dias'],['Entendi bem','em 7 dias'],['Dominei','em 14 dias']].map(([t,d],i)=>`<button class="g" onclick="rate(${i+1})">${t} <small>(revisar ${d})</small></button>`).join('')}</div>`;
const run=a&&running(a),pl=a?a.planned:(+dsel||25)*60,left=a?pl-elapsed(a):pl,C=2*Math.PI*78,pr=a?Math.min(1,elapsed(a)/pl):0;
const ring=`<svg class="ring" width="220" height="220" viewBox="0 0 200 200"><circle cx="100" cy="100" r="78" fill="none" stroke="var(--soft)" stroke-width="12"/><circle id="rg" cx="100" cy="100" r="78" fill="none" stroke="var(--hl)" stroke-width="12" stroke-linecap="round" stroke-dasharray="${C}" stroke-dashoffset="${C*pr}" transform="rotate(-90 100 100)"/><text x="100" y="108" text-anchor="middle" class="tm" id="tm">${fmt(left)}</text><text x="100" y="132" text-anchor="middle" class="sb">${a?(run?'Tempo restante':'Pausado'):'Duração do foco'}</text></svg>`;
if(a)return`${topbar('Modo foco',"go('study')")}${a.recover?`<div class="card c">Sessão interrompida (aba fechada). Contamos apenas até ${new Date(a.seen).toLocaleTimeString('pt-BR')}.<button class="p" style="margin-top:12px" onclick="S.active.recover=0;pause()">Recuperar e continuar</button><button class="g" onclick="finish()">Encerrar e salvar</button></div>`:''}
<div class="row" style="justify-content:center">${sq(ic(sj(a.subject).name,22),sj(a.subject).color)}<div><b>${esc(sj(a.subject).name)}</b><br><small>${esc(a.topic)}</small></div></div>${ring}<p class="hint c">Meta de ${Math.round(pl/60)} min. Pausas não contam.</p>
${a.recover?'':`<button class="p" onclick="pause()">${run?I('pause',18)+' Pausar':I('play',18)+' Continuar'}</button><button class="g" onclick="finish()">Finalizar e salvar</button><button class="g danger" style="border-color:transparent" onclick="finish(1)">Cancelar sessão</button>`}`;
return`${topbar('Iniciar estudo',"go('home')")}${ht('Escolha o que vai estudar e por quanto tempo.')}<div class="card f"><label for="ss">Matéria</label><select id="ss">${opts(fm.s)}</select><label for="st">Conteúdo</label><input id="st" placeholder="Ex: Equações do 2º grau" value="${esc(fm.t)}"><label>Duração em minutos</label><div class="chips">${[15,25,45,60].map(m=>`<button class="${dsel==m?'on':''}" onclick="setD(${m})">${m}</button>`).join('')}<button class="${[15,25,45,60].includes(+dsel)?'':'on'}" onclick="setD(+prompt('Minutos:','30')||25)">${[15,25,45,60].includes(+dsel)?'Outro':dsel}</button></div></div>${ring}<button class="p" onclick="startS()">${I('play',18)} Começar estudo</button>`},
rev(){const rv=S.reviews.filter(r=>(rtab=='pend')!=!!r.done).sort((x,y)=>x.due>y.due?1:-1);
return`${topbar('Revisões',rvf=='home'?"go('home')":"go('more')")}${ht('Revisar na hora certa ajuda a não esquecer o conteúdo. O sino mostra quantas estão para hoje.')}
<div class="card"><details open style="border:0;padding:0"><summary style="margin:0;color:var(--ink)">Como funciona</summary><ol class="how" style="margin-top:10px"><li>Estude pelo cronômetro (aba Estudos) e finalize a sessão.</li><li>O app pergunta o quanto você entendeu e agenda a revisão: não entendi = amanhã, entendi pouco = 2 dias, razoável = 4, bem = 7, dominei = 14.</li><li>Quando você revisar, toque no check. Ela vai para Concluídas.</li><li>Também dá para criar uma revisão manual no botão abaixo.</li></ol></details></div>
<button class="p" style="margin-bottom:14px" onclick="showRF=!showRF;render(1)">${I(showRF?'x':'plus',18)} ${showRF?'Fechar':'Nova revisão'}</button>
${showRF?`<form class="card f" onsubmit="event.preventDefault();Rv.add()"><label for="rt">Conteúdo a revisar</label><input id="rt" placeholder="Ex: Revolução Industrial" required><div class="row"><div class="grow f"><label for="rs">Matéria</label><select id="rs">${opts()}</select></div><div class="grow f"><label for="rd">Data</label><input id="rd" type="date" value="${today()}"></div></div><button class="p">Salvar revisão</button></form>`:''}
<div class="tabs">${[['pend','Pendentes'],['conc','Concluídas']].map(([k,l])=>`<button class="${rtab==k?'on':''}" onclick="rtab='${k}';render(1)">${l} (${S.reviews.filter(r=>(k=='pend')!=!!r.done).length})</button>`).join('')}</div>
<div class="card list">${rv.map(r=>`<div class="t"><div class="grow"><div class="tt">${esc(r.topic)}</div><div class="meta"><span><i class="dot" style="background:${sj(r.subject).color}"></i>${esc(sj(r.subject).name)}</span><span class="${rtab=='pend'&&r.due<today()?'late':''}">${r.due<=today()&&rtab=='pend'?(r.due<today()?'Atrasada':'Hoje'):dm(r.due)}</span></div></div><button class="mini" aria-label="${rtab=='pend'?'Marcar como revisada':'Reabrir revisão'}" style="${rtab=='pend'?'border:2px solid var(--bd);background:var(--hl);color:#fff;width:38px;height:38px':''}" onclick="Rv.toggle('${r.id}')">${I(rtab=='pend'?'check':'repeat',20)}</button></div>`).join('')||'<div class="empty">Nada por aqui.</div>'}</div><p class="hint c">Você já revisou ${rdone()} ${rdone()==1?'assunto':'assuntos'}.</p>`},
more(){if(sub=='rev')return P.rev();
if(sub=='acct')return`${topbar('Conta e nuvem',"go('more')")}${TK()?`<div class="card c">${sq(I('cloud',24),'var(--g)').replace('class="sq"','class="sq" style="margin:0 auto 10px;background:var(--hl)"')}<b>Sincronização ativa</b><br><small>${esc(localStorage['studyflow.email']||'')}</small><p class="hint" style="margin-top:10px">Suas alterações são salvas na nuvem automaticamente. Você pode abrir em outro aparelho e entrar com a mesma conta.</p><button class="p" onclick="pull().then(()=>alert('Sincronizado.'))">${I('repeat',18)} Sincronizar agora</button><button class="g" onclick="logout()">Sair da conta</button></div>`:`${ht('Crie uma conta para salvar seus dados na nuvem e usar o Tutor com IA. Sem conta, tudo continua salvo só neste aparelho.')}<form class="card f" onsubmit="event.preventDefault();authDo('login')"><label for="ae">E-mail</label><input id="ae" type="email" autocomplete="email" required><label for="ap">Senha (mínimo 6 caracteres)</label><input id="ap" type="password" autocomplete="current-password" required><div id="am" class="hint" style="margin:0" role="status"></div><button class="p">${I('user',18)} Entrar</button><button type="button" class="g" style="margin:0" onclick="authDo('register')">Criar conta</button><small class="c">Ao entrar, os dados da nuvem substituem os deste aparelho.</small></form>`}`;
if(sub=='tutor')return`${topbar('Tutor com IA',"go('more')")}<div class="msg">Olá, ${esc(name())}! Diga o que você quer aprender hoje. Posso explicar, criar exercícios, resumir e ajudar na revisão.</div>${chat.map(m=>`<div class="msg ${m.u?'u':''}">${esc(m.t)}</div>`).join('')}<div style="margin:16px 0">${[['book','Explicar conteúdo'],['tasks','Criar exercícios'],['doc','Fazer resumo'],['repeat','Revisar assunto'],['trophy','Simulado']].map(([i,b])=>`<button class="qb" onclick="$('#ti').value='${b}: ';$('#ti').focus()">${I(i,18)} ${b}</button>`).join('')}</div><form class="row" onsubmit="event.preventDefault();ask()"><input id="ti" placeholder="Digite sua dúvida aqui..." aria-label="Sua dúvida"><button class="circ" aria-label="Enviar">${I('send',18)}</button></form>`;
if(sub=='prog')return`${topbar('Progresso',"go('more')")}<div class="card"><div class="row">${sq(I('trophy',24))}<div class="grow"><div class="big">Nível ${lvl()}</div><div class="bar" style="margin-top:6px"><i style="width:${xp()%500/5}%"></i></div><small>${xp()%500} / 500 XP</small></div></div><p class="hint" style="margin:10px 0 0">1 minuto estudado = 1 XP. Revisão concluída = 20 XP.</p></div>
<div class="grid"><div class="card"><div class="big">${streak()}</div><small>dias seguidos</small></div><div class="card"><div class="big">${Math.max(longest(),streak())}</div><small>melhor sequência</small></div><div class="card"><div class="big">${hm(dur(()=>1))}</div><small>total estudado</small></div><div class="card"><div class="big">${S.sessions.length}</div><small>sessões</small></div></div>
<h2 style="margin:6px 0 4px">Conquistas</h2>${ht('Cada conquista é desbloqueada com seus registros reais.')}<div class="grid">${ACH().map(([i,n,d,v,t])=>`<div class="card ach ${v>=t?'':'off'}">${sq(I(i,22))}<b>${n}</b><small>${d}</small><div class="bar"><i style="width:${Math.min(100,v/t*100)}%"></i></div><small>${Math.min(Math.round(v),t)}/${t}${v>=t?', concluída':''}</small></div>`).join('')}</div>`;
const nr=dueRev();
return`<div class="head"><h1>Mais</h1></div>${mrow('repeat','Revisões',nr?nr+(nr==1?' conteúdo para rever hoje':' conteúdos para rever hoje'):'Conteúdos para rever',"openRev('more')")}${mrow('trophy','Progresso e conquistas','Nível, sequência e medalhas',"go('more','prog')")}${mrow('bot','Tutor com IA','Tire dúvidas e crie exercícios',"go('more','tutor')")}${mrow('cloud','Conta e nuvem',TK()?'Sincronização ativa':'Entre para salvar na nuvem',"go('more','acct')")}${themeRow()}
<h2 style="margin:22px 0 4px">Dados</h2>${ht('Tudo fica salvo neste aparelho (e na nuvem, se você entrou na conta).')}<button class="g" onclick="if(confirm('Apagar tudo (inclusive na nuvem, se estiver conectado) e começar do zero?')){S=empty();save();go('home')}">Apagar tudo e começar do zero</button><button class="g" onclick="if(confirm('Trocar seus dados pela demonstração?')){S=demo();save();go('home')}">Carregar dados de demonstração</button>`},
profile(){return`${topbar('Perfil',"go('home')")}<div class="card c" style="padding:26px 16px"><span class="circ av" style="width:84px;height:84px;font-size:38px;margin:0 auto 14px">${inicial()}</span><div class="f"><label for="nm" class="mu">Seu nome</label><input id="nm" value="${esc(name())}" style="text-align:center" onchange="S.user.name=this.value.trim()||'Dudu';save()"></div><div style="margin-top:16px"><b>Nível ${lvl()}</b> <small>${xp()%500}/500 XP</small></div><div class="bar"><i style="width:${xp()%500/5}%"></i></div></div>${mrow('trophy','Progresso e conquistas','Nível, sequência e medalhas',"go('more','prog')")}${mrow('cloud','Conta e nuvem',TK()?'Sincronização ativa':'Entre para salvar na nuvem',"go('more','acct')")}${themeRow()}${TK()?`<button class="g danger" onclick="logout()">Sair da conta</button>`:''}`}};
P.login=()=>`<div class="login"><div class="logo-mark">${I('book',36)}</div><h1>StudyFlow</h1><p class="mu">Matérias, tarefas, provas e revisões em um só lugar.</p><form class="card f" onsubmit="event.preventDefault();authDo('login')"><label for="ae">E-mail</label><input id="ae" type="email" autocomplete="email" placeholder="voce@email.com" required><label for="ap">Senha</label><input id="ap" type="password" autocomplete="current-password" placeholder="Mínimo 6 caracteres" required><div id="am" class="hint" style="margin:0" role="status"></div><button class="p">Entrar</button><button type="button" class="g" style="margin:0" onclick="authDo('register')">Criar conta</button></form><button class="skip" onclick="skipLogin()">Continuar sem conta</button><small class="c" style="display:block;margin-top:10px">Sem conta, seus dados ficam só neste aparelho e o Tutor com IA fica desligado.</small></div>`;
const gate=()=>!TK()&&!localStorage['sf.skip'],skipLogin=()=>{localStorage['sf.skip']=1;go('home')};
const setD=m=>{fm={s:$('#ss').value,t:$('#st').value};dsel=m;render(1)};

// ---------- tutor ----------
async function askAI(msg){if(!TK())return'Entre na sua conta (Mais, Conta e nuvem) para usar o tutor.';try{return(await api('POST','/tutor',{message:msg,history:chat.slice(0,-1).slice(-8)})).reply}catch(e){return e.message}}
async function ask(){const t=$('#ti').value.trim();if(!t)return;chat.push({u:1,t});const r=await askAI(t);chat.push({u:0,t:r||'Não consegui responder agora.'});render(1)}

// ---------- navegação ----------
const go=(p,sb='')=>{page=p;sub=sb;showRF=0;ttab='d3';rtab='pend';range='semana';fm={s:'',t:''};if(p!='timer')done=null;scrollTo(0,0);render(0)};
function render(keep){if(gate()){$('#nav').style.display='none';$('#app').innerHTML=P.login();return}$('#nav').style.display='';const items=[['home','home','Início'],['subjects','book','Matérias'],['tasks','tasks','Tarefas'],['study','chart','Estudos'],['more','more','Mais']],cur=page=='timer'?'study':page;
$('#nav').innerHTML=items.map(([k,i,l])=>`<a role="button" tabindex="0" aria-label="${l}" class="${cur==k?'on':''}" onclick="go('${k}')" onkeydown="if(event.key=='Enter'||event.key==' '){event.preventDefault();go('${k}')}">${I(i,22)}${l}</a>`).join('');
$('#app').innerHTML=P[page]()}

// ---------- nuvem (opcional): conta + sincronização ----------
const TK=()=>localStorage['studyflow.token'],setTK=(t,e)=>{t?(localStorage['studyflow.token']=t,localStorage['studyflow.email']=e):(localStorage.removeItem('studyflow.token'),localStorage.removeItem('studyflow.email'))};
// Endereço do servidor. No GitHub Pages não existe servidor, então só funciona com API_URL preenchido.
const base=()=>API_URL?API_URL.replace(/\/+$/,''):(location.hostname.endsWith('github.io')?null:'');
async function api(m,p,b){const u=base();if(u===null)throw new Error('A nuvem ainda não está ligada neste site. Falta colocar o endereço do servidor (API_URL) no começo do arquivo app.js.');
let r;try{r=await fetch(u+'/api'+p,{method:m,headers:{'Content-Type':'application/json',...(TK()?{Authorization:'Bearer '+TK()}:{})},body:b?JSON.stringify(b):undefined})}catch(e){throw new Error('Não consegui falar com o servidor. Confira a internet e o endereço (API_URL). No plano grátis do Render o servidor demora até 1 minuto para acordar: tente de novo.')}
const j=await r.json().catch(()=>null);if(!r.ok||!j)throw Object.assign(new Error((j&&j.error)||'O servidor respondeu algo inesperado (código '+r.status+'). Confira se o endereço em API_URL é o do servidor.'),{status:r.status,data:j||{}});return j}
const adopt=(d,t)=>{const a=S.active;S=d;fix();S.active=a||null;S.updatedAt=t;localStorage[K]=JSON.stringify(S);render(1)};
let pt;function push(){if(!TK())return;clearTimeout(pt);pt=setTimeout(async()=>{try{await api('PUT','/state',{data:{...S,active:null},updatedAt:S.updatedAt})}catch(e){if(e.status==409&&e.data&&e.data.data)adopt(e.data.data,e.data.updatedAt);else if(e.status==401)setTK()}},1500)}
async function pull(){if(!TK())return;try{const r=await api('GET','/state');if(r.data&&r.updatedAt>(S.updatedAt||0))adopt(r.data,r.updatedAt);else if(r.updatedAt<(S.updatedAt||0))push()}catch(e){if(e.status==401)setTK()}}
async function authDo(kind){const m=$('#am');m.style.color='var(--mu)';m.textContent='Conectando ao servidor... na primeira vez pode levar até 1 minuto.';
try{const r=await api('POST','/'+kind,{email:$('#ae').value,password:$('#ap').value,name:S.user.name});setTK(r.token,r.email);const c=await api('GET','/state');if(c.data)adopt(c.data,c.updatedAt);else save();go('home')}catch(e){m.style.color='var(--bad)';m.textContent=e.message}}
const logout=()=>{setTK();localStorage.removeItem('sf.skip');go('home')};
pull();
// se a aba foi fechada com sessão rodando, conta só até o último sinal de vida
if(S.active&&running(S.active)){S.active.segs.at(-1)[1]=S.active.seen;S.active.recover=true;save()}
render();
