const express=require('express'),path=require('path'),{Pool}=require('pg'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),rateLimit=require('express-rate-limit');
const {DATABASE_URL,JWT_SECRET,ANTHROPIC_API_KEY,ANTHROPIC_MODEL='claude-sonnet-5-5',PORT=3000}=process.env;
if(!DATABASE_URL||!JWT_SECRET){console.error('Faltam variáveis de ambiente: DATABASE_URL e JWT_SECRET');process.exit(1)}
const pool=new Pool({connectionString:DATABASE_URL,ssl:/\.render\.com/.test(DATABASE_URL)?{rejectUnauthorized:false}:false});
const app=express();app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'2mb'}));
const lim=rateLimit({windowMs:15*60*1000,max:40,standardHeaders:true,legacyHeaders:false,message:{error:'Muitas tentativas. Aguarde alguns minutos.'}});
const w=f=>(q,s)=>f(q,s).catch(e=>{console.error(e);s.status(500).json({error:'Erro no servidor. Tente novamente.'})});
const sign=u=>jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:'60d'});
const auth=(q,s,n)=>{try{q.user=jwt.verify((q.headers.authorization||'').slice(7),JWT_SECRET);n()}catch{s.status(401).json({error:'Sessão expirada. Entre novamente.'})}};
const mail=e=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e);
app.get('/api/health',(q,s)=>s.json({ok:true}));
app.post('/api/register',lim,w(async(q,s)=>{const email=String(q.body.email||'').trim().toLowerCase(),pw=String(q.body.password||''),name=String(q.body.name||'').slice(0,60);
if(!mail(email))return s.status(400).json({error:'E-mail inválido.'});if(pw.length<6)return s.status(400).json({error:'A senha precisa ter pelo menos 6 caracteres.'});
if((await pool.query('SELECT 1 FROM users WHERE email=$1',[email])).rowCount)return s.status(409).json({error:'E-mail já cadastrado.'});
const r=await pool.query('INSERT INTO users(email,name,password_hash) VALUES($1,$2,$3) RETURNING id,email',[email,name,await bcrypt.hash(pw,10)]);s.json({token:sign(r.rows[0]),email})}));
app.post('/api/login',lim,w(async(q,s)=>{const email=String(q.body.email||'').trim().toLowerCase(),r=await pool.query('SELECT * FROM users WHERE email=$1',[email]),u=r.rows[0];
if(!u||!(await bcrypt.compare(String(q.body.password||''),u.password_hash)))return s.status(401).json({error:'E-mail ou senha incorretos.'});s.json({token:sign(u),email:u.email})}));
app.get('/api/state',auth,w(async(q,s)=>{const r=await pool.query('SELECT data,updated_at FROM app_state WHERE user_id=$1',[q.user.id]);s.json(r.rows[0]?{data:r.rows[0].data,updatedAt:Number(r.rows[0].updated_at)}:{data:null,updatedAt:0})}));
app.put('/api/state',auth,w(async(q,s)=>{const{data,updatedAt}=q.body||{};if(!data||typeof data!=='object'||!Number.isFinite(updatedAt))return s.status(400).json({error:'Dados inválidos.'});
const r=await pool.query('INSERT INTO app_state(user_id,data,updated_at) VALUES($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET data=EXCLUDED.data,updated_at=EXCLUDED.updated_at WHERE app_state.updated_at<=EXCLUDED.updated_at RETURNING updated_at',[q.user.id,JSON.stringify(data),updatedAt]);
if(r.rowCount)return s.json({ok:true,updatedAt});const c=await pool.query('SELECT data,updated_at FROM app_state WHERE user_id=$1',[q.user.id]);s.status(409).json({error:'Há uma versão mais recente na nuvem.',data:c.rows[0].data,updatedAt:Number(c.rows[0].updated_at)})}));
app.post('/api/tutor',auth,lim,w(async(q,s)=>{if(!ANTHROPIC_API_KEY)return s.status(503).json({error:'Tutor ainda não configurado no servidor.'});
const msg=String(q.body.message||'').slice(0,2000),hist=(Array.isArray(q.body.history)?q.body.history:[]).slice(-8).map(m=>({role:m.u?'user':'assistant',content:String(m.t||'').slice(0,2000)})).filter(m=>m.content);
const msgs=[...hist,{role:'user',content:msg}].reduce((a,m)=>{a.at(-1)?.role===m.role?a.at(-1).content+='\n'+m.content:a.push({...m});return a},[]);if(msgs[0].role!=='user')msgs.shift();
const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:ANTHROPIC_MODEL,max_tokens:900,system:'Você é o tutor do StudyFlow, para estudantes do Ensino Médio no Brasil. Responda em português do Brasil, de forma clara, curta e didática, com exemplos. Ao criar exercícios, não entregue o gabarito junto: peça que o aluno tente primeiro.',messages:msgs})});
const j=await r.json();if(!r.ok){console.error(j);return s.status(502).json({error:'O tutor não conseguiu responder agora.'})}s.json({reply:(j.content||[]).map(b=>b.text||'').join('')})}));
app.use(express.static(path.join(__dirname,'public')));
(async()=>{await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS app_state(user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,data JSONB NOT NULL,updated_at BIGINT NOT NULL)`);
app.listen(PORT,()=>console.log('StudyFlow rodando na porta '+PORT))})().catch(e=>{console.error('Falha ao iniciar:',e.message);process.exit(1)});
